"""Composition root for the FastAPI service (issue #22).

``service.main`` is the ONE place that reads the environment
(:func:`service.config.load_service_config`), builds the REAL dependencies
(the live :class:`~rag.provider.AnthropicAdapter`, the retrieval / chart
seams, and the merged #13 citation-support validator), and hands them to
:func:`service.app.create_app`. Everything below it takes injected
dependencies — so the service package stays testable on fakes with no
network, and importing ``service.*`` never loads torch/docling/fitz.

The heavy stack (bge embedder + reranker, chart pack frames, dataset
manifest) is constructed LAZILY behind the injected seams: process
startup, ``/health``, the paused read-only state and the unit tests never
pay a multi-GB import for a code path that never infers (issue #125 /
IMPLEMENTATION.md §1). ``rag.citation_validator`` is imported here and
NOWHERE else in ``service.*`` (the injected #13 seam).

Served as ``uvicorn service.main:app`` (see docker-compose.yml /
Dockerfile): the module-level :data:`app` is built from the environment
when configured, and degrades to a health-only app when it is not (so
``import service.main`` and the unit tests never require the deploy env).
:func:`create_service_app` is the equivalent explicit ASGI factory.
"""

from __future__ import annotations

import os
from collections import OrderedDict
from collections.abc import Callable, Mapping
from datetime import UTC, datetime
from functools import partial
from pathlib import Path
from typing import Any

from service.app import ServiceDeps, ServiceStartupError, create_app
from service.config import (
    ENV_ANTHROPIC_API_KEY,
    ENV_PROVIDER,
    PROVIDER_REPLAY,
    ServiceConfig,
    ServiceConfigError,
    load_service_config,
)

__all__ = [
    "app",
    "build_service_deps",
    "create_service_app",
    "validate_deployment_artifacts",
]

# Optional deployment artifact locations (not critical config: the paused
# read-only stack never reads them). Each has a container-friendly default.
ENV_CHART_STORE_DIR = "CLIMATE_CHAT_CHART_STORE_DIR"
ENV_DATASET_MANIFEST = "CLIMATE_CHAT_DATASET_MANIFEST"
ENV_CHART_PACK_DIR = "CLIMATE_CHAT_CHART_PACK_DIR"
ENV_THRESHOLD_ARTIFACT = "CLIMATE_CHAT_THRESHOLD_ARTIFACT"

#: Repo root (service/main.py -> parents[1]); the transparency pages are
#: built from the committed single sources of truth below it.
_REPO_ROOT = Path(__file__).resolve().parents[1]
#: The single sources of truth the #19 transparency pages render from.
_CORPUS_MANIFEST_PATH = _REPO_ROOT / "corpus" / "manifest.yaml"
_DATASETS_MANIFEST_PATH = _REPO_ROOT / "datasets" / "manifest.yaml"
_EVAL_RESULTS_PATH = _REPO_ROOT / "evals" / "RESULTS.md"


def _utc_now() -> datetime:
    """The service's only wall-clock source (aware UTC)."""
    return datetime.now(UTC)


def create_service_app() -> Any:
    """ASGI factory: read the environment, build real deps, wire the app."""
    config = load_service_config(os.environ)
    deps = build_service_deps(config)
    # A deploy that cannot serve what it promises fails loudly at BOOT
    # (#214/#216), before /health can mask it — not with a per-request 500.
    validate_deployment_artifacts(
        os.environ,
        index_corpus_version=deps.index_corpus_version(),
        stored_chart_specs=deps.chart_spec_store.has_specs(),
        eval_results_path=_EVAL_RESULTS_PATH,
    )
    return create_app(config, deps)


def validate_deployment_artifacts(
    env: Mapping[str, str],
    *,
    index_corpus_version: str | None,
    stored_chart_specs: bool,
    eval_results_path: Path | None = None,
) -> None:
    """Startup validation of the artifact env contract (#214, #216, #249).

    Pure over ``env`` (no os.environ read; ``eval_results_path`` is an
    injected path, defaulting to the repo's ``evals/RESULTS.md`` when
    ``None``). Three rules, mirroring ``load_service_config``'s
    name-every-offender discipline; every violation is collected and
    raised at once as :class:`service.app.ServiceStartupError` naming
    each offending variable/path — a deploy that cannot serve what it
    promises fails loudly at BOOT, never with a per-request 500:

    - **Permalinks must be servable (#214, ADR-015).** When the chart
      spec store already holds specs (``stored_chart_specs`` — flagship
      permalinks landed at release, or specs generated by an earlier
      live run), re-rendering them requires the dataset manifest and
      the landed chart pack: :data:`ENV_DATASET_MANIFEST` must name a
      readable file and :data:`ENV_CHART_PACK_DIR` a readable
      directory. DECISION (flagged for ratification): the render inputs
      are REQUIRED deployment artifacts for any stack with stored
      permalinks — including the paused read-only stack — rather than
      persisting rendered artefacts beside each spec (which would
      duplicate the pack per spec and contradict §3.7's ~1 KB
      spec-only permalink design). An empty store (the dev compose
      stub) requires nothing and serves clean 404s.
    - **Live generation must be startable (#216).** When
      ``index_corpus_version`` is not None (a real ingested deploy),
      first-query dependencies must be present and readable at boot:
      :data:`ENV_THRESHOLD_ARTIFACT` (file), plus the manifest + pack
      above (chart generation renders immediately).
    - **A live deploy must serve the REAL transparency pages (#249).**
      When ``index_corpus_version`` is not None, ``eval_results_path``
      (the published ``evals/RESULTS.md`` the #19 transparency build
      renders from) must be a readable file; a missing/unreadable file
      is an offender NAMED BY ITS PATH in the refusal. Only the
      un-ingested dev/compose-smoke stack (``index_corpus_version is
      None`` — the same #215 zero-config boundary as the read-only
      tolerance above) and the replay-provider stack (the #231 seeded
      smoke: ``CLIMATE_CHAT_PROVIDER=replay`` is explicit, never
      implicit, and by construction not a public deploy) may boot
      without it and keep serving the honestly-marked interim
      placeholder pages.

    ``create_service_app`` runs this after loading config, before
    serving.
    """
    offending: list[str] = []

    def require_file(name: str) -> None:
        value = env.get(name)
        if not value or not Path(value).is_file():
            offending.append(name)

    def require_dir(name: str) -> None:
        value = env.get(name)
        if not value or not Path(value).is_dir():
            offending.append(name)

    # Permalinks must be servable: re-rendering a stored spec needs the
    # manifest + landed pack (the ~1 KB spec is not the data). Required for
    # ANY stack with stored specs, paused included (#214, ratified).
    render_inputs_required = stored_chart_specs
    # A live (index-recorded) deploy must be able to answer the first query
    # without a per-request 500: the threshold artifact AND the render
    # inputs must be readable at boot (#216).
    live_generation = index_corpus_version is not None
    if live_generation:
        require_file(ENV_THRESHOLD_ARTIFACT)

    if render_inputs_required or live_generation:
        require_file(ENV_DATASET_MANIFEST)
        require_dir(ENV_CHART_PACK_DIR)

    # #249: a live (index-recorded) deploy must serve the REAL transparency
    # pages — the published eval results the #19 build renders from must be
    # a readable file, NAMED BY ITS PATH in the refusal. Only the
    # un-ingested dev/compose-smoke stack (index None — the #215 zero-config
    # boundary) may boot without it and keep serving the honestly-marked
    # interim placeholder pages.
    # The replay-provider stack (the #231 seeded smoke: CLIMATE_CHAT_PROVIDER
    # explicitly 'replay', never selected implicitly, typos refused) is by
    # construction not a public live deploy — it cannot answer an unpinned
    # question. Its ingested index therefore does not oblige the published
    # eval results; the honestly-marked interim placeholders keep serving.
    replay_stack = str(env.get(ENV_PROVIDER, "")).strip().lower() == PROVIDER_REPLAY
    if live_generation and not replay_stack:
        results_path = eval_results_path if eval_results_path is not None else _EVAL_RESULTS_PATH
        if not results_path.is_file():
            offending.append(str(results_path))

    if offending:
        # Name every offender at once (load_service_config's discipline).
        raise ServiceStartupError(
            "deployment artifact validation refused — missing or unreadable "
            "artifacts required to serve this stack: " + ", ".join(dict.fromkeys(offending))
        )


def _health_only_app() -> Any:
    """A minimal ``/health`` app for a keyless/env-less process.

    ``service.main:app`` must import without the ``CLIMATE_CHAT_*``
    environment (unit tests, ``import service.main``): when config is
    absent it degrades to a health-only app rather than crashing at
    import. A correctly-configured container always gets the full app.
    """
    from fastapi import FastAPI

    fallback = FastAPI(title="Let's Talk About the Climate Emergency — API (unconfigured)")

    @fallback.get("/health")
    def health() -> dict[str, str]:
        return {"status": "ok"}

    return fallback


def _build_module_app() -> Any:
    try:
        return create_service_app()
    except ServiceConfigError:
        # The health-only fallback is ONLY for the fully-absent deploy env
        # (the import / unit-test context; a bare ANTHROPIC_API_KEY on a dev
        # box is not a deploy). A PARTIAL or invalid CLIMATE_CHAT_* env is a
        # real misconfiguration: re-raise so the container crashes and the
        # platform reports the failed deploy, rather than booting a
        # deceptive health-only app that answers {"status": "ok"} while
        # every real route 404s (#215).
        if any(name.startswith("CLIMATE_CHAT_") for name in os.environ):
            raise
        return _health_only_app()


def build_service_deps(
    config: ServiceConfig,
    *,
    clock: Callable[[], datetime] = _utc_now,
) -> ServiceDeps:
    """Assemble the real, injected dependency bundle for :func:`create_app`."""
    # Imports deferred to call time (never module import time): the anthropic
    # SDK and the #13 validator are live-path dependencies, and none of these
    # load torch at import — the model weights load lazily on first inference.
    from rag.citation_validator import (
        ValidatorConfig,
        append_validation_events,
        exchange_log_record,
        validate_exchange,
    )
    from service.budget import SpendTracker
    from service.chart_store import ChartSpecStore
    from service.config import PROVIDER_REPLAY
    from service.exchange_log import ExchangeLog
    from service.rate_limit import RateLimiter, RotatingSaltProvider
    from service.starter_cache import load_starter_cache

    # The composition-root provider switch (finding #231): the live
    # Anthropic transport by default, or the deterministic ReplayAdapter over
    # checked-in fixtures for the live-path smoke tier. Replay makes zero
    # live calls by construction — no key is read or needed.
    if config.provider == PROVIDER_REPLAY:
        from rag.provider import ReplayAdapter

        adapter: Any = ReplayAdapter(Path(config.replay_dir))
    else:
        from rag.provider import AnthropicAdapter

        # The key travels from the environment straight to the transport; it
        # is never stored on ServiceConfig and never logged.
        adapter = AnthropicAdapter(api_key=os.environ.get(ENV_ANTHROPIC_API_KEY))

    spend_tracker = SpendTracker(
        daily_budget_usd=config.daily_budget_usd,
        opus_subcap_usd=config.opus_subcap_usd,
        clock=clock,
        # Journal spend under the (volume-backed) log dir so a restart or
        # crash-loop cannot forget the day's spend and un-pause the cap
        # (#217). Reads the current UTC day back at construction.
        state_dir=Path(config.log_dir) / "spend-state",
    )
    rate_limiter = RateLimiter(
        clock=clock,
        salts=RotatingSaltProvider(clock),
        max_requests=config.rate_limit_per_minute,
    )
    exchange_log = ExchangeLog(Path(config.log_dir) / "exchanges.jsonl", clock=clock)
    starter_cache = load_starter_cache(Path(config.starter_cache_dir))

    chart_store_dir = os.environ.get(ENV_CHART_STORE_DIR) or str(
        Path(config.log_dir) / "chart-specs"
    )
    chart_spec_store = ChartSpecStore(Path(chart_store_dir))

    # The merged #13 seam, bound with the live adapter (the ONLY place the
    # service imports rag.citation_validator).
    validator_config = ValidatorConfig()
    bound_validate = partial(validate_exchange, adapter, config=validator_config)

    # Issue #57 / finding #287: ONE lazy bge-m3 holder per process, shared by
    # the semantic cache and the retrieval query-embedding seam. Both load
    # the SAME multi-GB weights, so two instances would double the heaviest
    # model's footprint on the DESIGN §9 <~£20/month box (the difference
    # between serving and OOM). The embedder still loads LAZILY on first
    # encode — wiring must not pull weights at construction.
    embedder = _LazyEmbedder()

    # The semantic response cache is wired ONLY when enabled (default ON).
    semantic_cache: Any = None
    if config.semantic_cache_enabled:
        from service.semantic_cache import SemanticCache

        semantic_cache = SemanticCache(
            embedding_model=embedder,
            corpus_version=config.corpus_version,
            clock=clock,
        )

    return ServiceDeps(
        adapter=adapter,
        retrieve=_LazyRetrieval(config, embedder),
        plan_chart=_LazyPlanner(config, adapter),
        render_chart=_LazyRenderer(config),
        validate_exchange=lambda result, sse_events: bound_validate(result, sse_events),
        append_validation_events=append_validation_events,
        exchange_log_record=exchange_log_record,
        spend_tracker=spend_tracker,
        rate_limiter=rate_limiter,
        exchange_log=exchange_log,
        starter_cache=starter_cache,
        chart_spec_store=chart_spec_store,
        index_corpus_version=_make_index_version_reader(config),
        clock=clock,
        # The #19 transparency pages, built once at startup from the
        # committed sources of truth (retires the interim placeholders).
        transparency=_build_transparency_pages(config),
        # The #57 semantic response cache (None when disabled).
        semantic_cache=semantic_cache,
    )


def _build_transparency_pages(config: ServiceConfig) -> Any:
    """Build the #19 transparency pages from the committed sources of truth.

    Rendered ONCE at startup (like ``/health``, they then serve for $0 in
    both modes). Wiring the real pages retires the interim placeholders in
    ``service.app``. Returns ``None`` — keeping those placeholders — only in
    the pre-release / dev-compose state where the published
    ``evals/RESULTS.md`` has not landed yet (the same read-only tolerance as
    an un-ingested index); a present-but-unreadable results file or manifest
    still fails the build loudly (``TransparencyBuildError``).
    """
    from service.transparency import build_transparency_pages

    if not _EVAL_RESULTS_PATH.is_file():
        return None
    return build_transparency_pages(
        corpus_manifest_path=_CORPUS_MANIFEST_PATH,
        datasets_manifest_path=_DATASETS_MANIFEST_PATH,
        eval_results_path=_EVAL_RESULTS_PATH,
        corpus_vintage=config.corpus_vintage,
    )


def _make_index_version_reader(config: ServiceConfig) -> Callable[[], str | None]:
    """A reader for the recorded index corpus version.

    Returns ``None`` on ANY failure to reach or read the index (no
    collection yet, Qdrant not up): an absent index is a legitimate
    read-only start (ratified #22.5), never a crash — a genuine version
    MISMATCH is what :func:`create_app` refuses on.
    """

    def read_version() -> str | None:
        try:
            from qdrant_client import QdrantClient

            from rag.indexing import get_index_corpus_version

            client = QdrantClient(url=config.qdrant_url)
            return get_index_corpus_version(client, config.collection_name)
        except Exception:
            return None

    return read_version


class _LazyEmbedder:
    """One process-wide LOCAL bge-m3 holder, building the weights on first use.

    Constructing ``Bgem3EmbeddingModel`` loads torch + multi-GB weights;
    deferring that here keeps startup, ``/health`` and the paused state
    free of it (issue #125), exactly like ``_LazyRetrieval``. Proxies the
    FULL ``rag.indexing.EmbeddingModel`` seam — the semantic cache only
    calls ``encode``, but the retrieval query path also reads
    ``model_id``/``revision``/``dense_dim`` (checking the query model
    against the index before embedding), so a partial proxy would break
    real retrieval. Sharing this ONE instance across both seams keeps a
    single copy of the multi-GB weights per process (finding #287).
    """

    def __init__(self) -> None:
        self._model: Any = None

    def _ensure(self) -> Any:
        if self._model is None:
            from rag.indexing import Bgem3EmbeddingModel

            self._model = Bgem3EmbeddingModel()
        return self._model

    @property
    def model_id(self) -> str:
        return self._ensure().model_id

    @property
    def revision(self) -> str:
        return self._ensure().revision

    @property
    def dense_dim(self) -> int:
        return self._ensure().dense_dim

    def encode(self, texts: Any) -> Any:
        return self._ensure().encode(texts)


class _LazyRetrieval:
    """The injected retrieval seam, building its heavy models on first call.

    Constructing the bge embedder + reranker loads torch and multi-GB
    weights; deferring that here keeps startup, ``/health`` and the paused
    state free of it (issue #125). Requires the calibrated refusal
    threshold artifact and an ingested index — both release/ingestion
    outputs (see service/DEPLOYMENT.md).
    """

    def __init__(self, config: ServiceConfig, embedder: Any) -> None:
        self._config = config
        # The one shared process-wide lazy bge-m3 holder (finding #287): the
        # same instance the semantic cache embeds through, so a live process
        # loads the weights ONCE.
        self._embedder = embedder
        self._built: dict[str, Any] | None = None

    def _build(self) -> dict[str, Any]:
        from qdrant_client import QdrantClient

        from rag.retrieval import BgeRerankerV2M3, RetrievalConfig, load_threshold_artifact

        threshold_path = os.environ.get(ENV_THRESHOLD_ARTIFACT)
        if not threshold_path:
            raise RuntimeError(
                f"live retrieval requires {ENV_THRESHOLD_ARTIFACT} (the calibrated "
                "refusal threshold artifact) — see service/DEPLOYMENT.md"
            )
        calibration = load_threshold_artifact(Path(threshold_path))
        return {
            "client": QdrantClient(url=self._config.qdrant_url),
            "embedder": self._embedder,
            "reranker": BgeRerankerV2M3(),
            "config": RetrievalConfig(
                refusal_threshold=calibration.threshold,
                corpus_coverage=(),
            ),
        }

    def __call__(self, decision: Any) -> Any:
        from rag.retrieval import retrieve

        if self._built is None:
            self._built = self._build()
        built = self._built
        return retrieve(
            built["client"],
            self._config.collection_name,
            decision,
            embedding_model=built["embedder"],
            reranker=built["reranker"],
            config=built["config"],
            expected_corpus_version=self._config.corpus_version,
        )


class _LazyPlanner:
    """The injected chart-planner seam (one structured adapter call)."""

    def __init__(self, config: ServiceConfig, adapter: Any) -> None:
        self._config = config
        self._adapter = adapter
        self._manifest: Any = None

    def _manifest_path(self) -> Path:
        manifest = os.environ.get(ENV_DATASET_MANIFEST)
        if not manifest:
            raise RuntimeError(
                f"chart planning requires {ENV_DATASET_MANIFEST} (the dataset "
                "manifest) — see service/DEPLOYMENT.md"
            )
        return Path(manifest)

    def __call__(self, chart_request: str) -> Any:
        from charts.planner import plan_chart_request

        if self._manifest is None:
            self._manifest = self._manifest_path()
        return plan_chart_request(self._adapter, chart_request, self._manifest)


class _LazyRenderer:
    """The injected renderer seam (pure spec -> artefact; no fetch).

    A chart view fans out to three endpoints (``/chart/{hash}``, ``.csv``,
    ``.svg``), each of which rendered the whole artifact afresh. Since a
    permalinked spec is immutable by its hash and the frames/manifest/site
    are process-fixed, the artifact is a pure function of the spec hash, so
    it is cached here (finding #297): the JSON+CSV+SVG of one view now share
    a single render. Bounded LRU so a long-lived server can't grow the cache
    without limit."""

    _ARTIFACT_CACHE_MAX = 128

    def __init__(self, config: ServiceConfig) -> None:
        self._config = config
        self._built: dict[str, Any] | None = None
        self._artifacts: OrderedDict[str, Any] = OrderedDict()

    def _build(self) -> dict[str, Any]:
        # charts.pack.load_chart_pack_frames is the ONE frame-loading rule,
        # shared with the smoke seeder (scripts/seed_smoke_stack.py) so the
        # two cannot drift; it lives in charts.pack so consumers never pay
        # this module's import-time app construction.
        from charts.pack import load_chart_pack_frames

        manifest_path = os.environ.get(ENV_DATASET_MANIFEST)
        pack_dir = os.environ.get(ENV_CHART_PACK_DIR)
        if not manifest_path or not pack_dir:
            raise RuntimeError(
                f"chart rendering requires {ENV_DATASET_MANIFEST} and "
                f"{ENV_CHART_PACK_DIR} (the dataset manifest + landed chart pack) "
                "— see service/DEPLOYMENT.md"
            )
        raw, frames = load_chart_pack_frames(Path(manifest_path), Path(pack_dir))
        return {"manifest": raw, "frames": frames}

    def __call__(self, spec: Mapping[str, Any]) -> Any:
        from charts.render import render_chart, spec_hash

        key = spec_hash(spec)
        cached = self._artifacts.get(key)
        if cached is not None:
            self._artifacts.move_to_end(key)
            return cached

        if self._built is None:
            self._built = self._build()
        artifact = render_chart(
            spec,
            frames=self._built["frames"],
            manifest=self._built["manifest"],
            site_url=self._config.site_url,
        )
        self._artifacts[key] = artifact
        if len(self._artifacts) > self._ARTIFACT_CACHE_MAX:
            self._artifacts.popitem(last=False)
        return artifact


#: The ASGI app uvicorn serves (``uvicorn service.main:app``). Built from
#: the environment when configured, health-only otherwise. Assigned at the
#: END of the module so every helper it calls is already defined.
app = _build_module_app()
