"""ChartSpec: JSON Schema, pure-code validator and canonical spec hashing (issue #15).

This module freezes the chart vocabulary (DESIGN §3.7 as amended; ADR-020;
the ten binding vocabulary amendments filed on issue #15 from the #4 spike;
review findings #47/#48/#50/#52). The LLM chart planner (#16) writes a
ChartSpec — never code — and everything here is pure: no network, no
filesystem reach-around, no data loading (IMPLEMENTATION.md §1).

Vocabulary decisions frozen here
--------------------------------

- **Chart types** (:data:`CHART_TYPES`): the five MVP types. The
  context+recent-inset panel pair is a *layout wrapper* (vocabulary
  amendment 4): ``panels.context`` / ``panels.recent`` each carry a
  ``label`` and ``time_range_ce``; the series themselves carry
  ``axis: left|right`` and are drawn in both panels.
- **Transforms**: the generic four (:data:`TRANSFORM_OPS`) live in a
  per-series ``transforms`` list of ``{op: ..., <params>}`` objects; the
  three flagship transforms are dedicated fields with manifest-anchored
  semantics — ``splice_series`` + ``splice_pair_id`` (+ mandatory
  ``overlap_policy``), ``rebaseline_to`` and the spec-level ``time_axis``.
- **Manifest is the source of truth** (ADR-020): splice membership, splice
  year, overlap policy, rebaseline apply-to/alignment period and the
  alignment disclosure are curation-time decisions recorded in
  ``datasets/manifest.yaml``. The validator *cross-checks* the spec against
  the manifest and refuses any disagreement; it never re-decides them.
- **No caption in the spec**: captions (sources, licences, access date,
  site URL) are generated by the renderer from the manifest attribution /
  licence strings and deployment config (vocabulary amendment 9). Free
  caption text in an LLM-authored spec is a drift **and injection** vector,
  so the schema has no ``caption`` property at all.
- **Closed everywhere**: ``additionalProperties: false`` throughout (the
  only tolerated extra is the top-level ``_meta`` provenance block, which
  is semantically inert and excluded from hashing). Annotation *placement*
  is fixed semantics — splice rules render in every panel they intersect,
  text labels render once in the context panel (amendment 7) — so there is
  no placement field for a spec to author.
"""

from __future__ import annotations

import hashlib
import json
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from typing import Any

from jsonschema import Draft202012Validator

from charts import pack

#: The closed chart-type vocabulary (DESIGN §3.7 MVP list; warming stripes
#: is Phase 2 and deliberately NOT here).
CHART_TYPES = frozenset(
    {
        "line",
        "area",
        "bar",
        "dual_axis_line",
        "context_recent_inset",
    }
)

#: The closed generic-transform vocabulary (`transforms[*].op`). The three
#: flagship transforms (splice, rebaseline, BP→CE time axis) are dedicated
#: spec fields, not list entries, because their parameters are
#: manifest-anchored rather than LLM-choosable.
TRANSFORM_OPS = frozenset(
    {
        "resample",
        "anomaly_vs_baseline",
        "rolling_mean",
        "unit_conversion",
    }
)

#: The closed overlap-policy vocabulary (review finding #47). What a spec
#: may carry for a given pair is further narrowed to the *manifest-legal*
#: value recorded in that pair's ``overlap.policy`` — the curation-time
#: decision about what happens to overlapping source samples.
OVERLAP_POLICIES = frozenset(
    {
        "prefer_instrumental",
        "prefer_paleo",
        "show_both",
    }
)


@dataclass(frozen=True)
class SpecViolation:
    """One actionable refusal: the spec path that is wrong, and why.

    ``path`` is rooted at the spec document and uses dotted/bracketed
    syntax (``chart_type``, ``series[1].rebaseline_to.alignment_period_ce``,
    ``panels.recent.time_range_ce``). ``reason`` states what was found and
    what would be legal — never a bare "invalid".
    """

    path: str
    reason: str


class ChartSpecError(ValueError):
    """A refused ChartSpec. Carries every violation found (the validator

    collects; it does not stop at the first), and the exception message
    contains each violation's path so a log line alone is actionable
    (issue #15 acceptance: rejection messages name field + reason).
    """

    def __init__(self, violations: tuple[SpecViolation, ...] | list[SpecViolation]) -> None:
        self.violations: tuple[SpecViolation, ...] = tuple(violations)
        super().__init__("; ".join(f"{v.path}: {v.reason}" for v in self.violations))


# ---------------------------------------------------------------------------
# The frozen JSON Schema (draft 2020-12)
# ---------------------------------------------------------------------------


def chartspec_schema() -> dict[str, Any]:
    """The ChartSpec JSON Schema (draft 2020-12) — the frozen vocabulary.

    Structural contract (pinned by tests):

    - ``chart_type`` enum is exactly :data:`CHART_TYPES`;
    - ``transforms[*].op`` enum is exactly :data:`TRANSFORM_OPS`;
    - ``overlap_policy`` enum is exactly :data:`OVERLAP_POLICIES`;
    - ``time_axis`` is ``{calendar: "CE" (const), convert_bp: bool}`` —
      BCE-aware axis labelling (negative years as "8000 BCE", no year-0
      tick) is *time_axis semantics* owned by the renderer, so there is no
      per-spec label-format/styling field (vocabulary amendment 8);
    - ``rebaseline_to`` requires ``apply_to``, ``alignment_period_ce`` and
      ``alignment_disclosure`` (review finding #50: the alignment method
      must reach the artefact, not only repo files);
    - a series carries exactly one data source: ``dataset`` XOR
      (``splice_series`` + ``splice_pair_id``);
    - ``uncertainty_band`` is ``{lower, upper, source: <dataset_id>}`` —
      bands attach to a splice *member* (amendment 6);
    - no ``caption`` property anywhere (amendment 9 — manifest-generated);
    - ``additionalProperties: false`` at every level; only the top-level
      ``_meta`` block is admitted (and ignored semantically).

    Pure; returns a plain dict, safe to serialise for the planner prompt.
    """
    year_pair = {
        "type": "array",
        "items": {"type": "number"},
        "minItems": 2,
        "maxItems": 2,
    }
    # A generic per-series transform. The conversion arithmetic is
    # code-owned: a unit_conversion carries only ``to_unit`` (never an
    # LLM-authored ``factor`` — that would be a silent scaling attack).
    transform = {
        "type": "object",
        "additionalProperties": False,
        "required": ["op"],
        "properties": {
            "op": {"enum": sorted(TRANSFORM_OPS)},
            "window_years": {"type": "number"},
            "to_unit": {"type": "string"},
        },
    }
    splice_point = {
        "type": "object",
        "additionalProperties": False,
        "required": ["year_ce", "label"],
        "properties": {
            "year_ce": {"type": "number"},
            "label": {"type": "string"},
        },
    }
    non_zero_baseline = {
        "type": "object",
        "additionalProperties": False,
        "required": ["label"],
        "properties": {"label": {"type": "string"}},
    }
    # Annotation *placement* is fixed semantics (amendment 7), so there is
    # no placement field: the only annotations a spec authors are the
    # splice point + resolution note (mandatory for a splice) and the
    # non-zero-baseline disclosure.
    annotations = {
        "type": "object",
        "additionalProperties": False,
        "properties": {
            "splice_point": splice_point,
            "resolution_note": {"type": "string"},
            "non_zero_baseline": non_zero_baseline,
        },
    }
    rebaseline_to = {
        "type": "object",
        "additionalProperties": False,
        "required": ["apply_to", "alignment_period_ce", "alignment_disclosure"],
        "properties": {
            "apply_to": {"type": "string"},
            "alignment_period_ce": year_pair,
            "alignment_disclosure": {"type": "string"},
        },
    }
    uncertainty_band = {
        "type": "object",
        "additionalProperties": False,
        "required": ["lower", "upper", "source"],
        "properties": {
            "lower": {"type": "string"},
            "upper": {"type": "string"},
            "source": {"type": "string"},
        },
    }
    baseline = {
        "type": "object",
        "additionalProperties": False,
        "required": ["value", "label"],
        "properties": {
            "value": {"type": "number"},
            "label": {"type": "string"},
        },
    }
    series = {
        "type": "object",
        "additionalProperties": False,
        "required": ["id", "label", "unit"],
        "properties": {
            "id": {"type": "string"},
            "label": {"type": "string"},
            "axis": {"enum": ["left", "right"]},
            "color": {"type": "string"},
            "unit": {"type": "string"},
            "dataset": {"type": "string"},
            "splice_series": {
                "type": "array",
                "items": {"type": "string"},
                "minItems": 2,
                "maxItems": 2,
            },
            "splice_pair_id": {"type": "string"},
            "overlap_policy": {"enum": sorted(OVERLAP_POLICIES)},
            "rebaseline_to": rebaseline_to,
            "scale_domain": year_pair,
            "baseline": baseline,
            "annotations": annotations,
            "uncertainty_band": uncertainty_band,
            "transforms": {"type": "array", "items": transform},
        },
    }
    panel = {
        "type": "object",
        "additionalProperties": False,
        "required": ["label", "time_range_ce"],
        "properties": {
            "label": {"type": "string"},
            "time_range_ce": year_pair,
            "shared_y_scale_with": {"type": "string"},
        },
    }
    panels = {
        "type": "object",
        "additionalProperties": False,
        "required": ["context", "recent"],
        "properties": {
            "context": panel,
            "recent": panel,
        },
    }
    time_axis = {
        "type": "object",
        "additionalProperties": False,
        "required": ["calendar", "convert_bp"],
        "properties": {
            "calendar": {"const": "CE"},
            "convert_bp": {"type": "boolean"},
        },
    }
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "ChartSpec",
        "type": "object",
        "additionalProperties": False,
        "required": ["spec_version", "chart_id", "chart_type", "title", "series"],
        "properties": {
            "spec_version": {"type": "string"},
            "chart_id": {"type": "string"},
            "chart_type": {"enum": sorted(CHART_TYPES)},
            "title": {"type": "string"},
            "subtitle": {"type": "string"},
            "time_range_ce": year_pair,
            "time_axis": time_axis,
            "panels": panels,
            "series": {"type": "array", "items": series, "minItems": 1},
            # Semantically inert provenance/sign-off block: admitted and
            # excluded from hashing, arbitrary content.
            "_meta": {"type": "object"},
        },
    }


# ---------------------------------------------------------------------------
# Structural validation: JSON Schema errors -> SpecViolation
# ---------------------------------------------------------------------------


def _format_path(parts: Sequence[Any]) -> str:
    """Render a JSON-Schema absolute path (keys + array indices) as the
    dotted/bracketed spec-path syntax the refusal messages use."""
    out = ""
    for part in parts:
        if isinstance(part, int):
            out += f"[{part}]"
        elif out == "":
            out = str(part)
        else:
            out += f".{part}"
    return out


def _structural_violations(spec: Mapping[str, Any]) -> list[SpecViolation]:
    """Every JSON-Schema violation, each mapped to an actionable
    (path, reason) rooted at the offending property."""
    validator = Draft202012Validator(chartspec_schema())
    violations: list[SpecViolation] = []
    for error in validator.iter_errors(spec):
        base = list(error.absolute_path)
        if error.validator == "additionalProperties":
            allowed = set((error.schema or {}).get("properties", {}))
            instance = error.instance if isinstance(error.instance, Mapping) else {}
            for key in sorted(set(instance) - allowed):
                violations.append(
                    SpecViolation(
                        _format_path([*base, key]),
                        f"unknown property {key!r} is not in the frozen ChartSpec "
                        "vocabulary (additionalProperties: false — the LLM cannot "
                        "smuggle fields past the closed schema)",
                    )
                )
        elif error.validator == "required":
            required = error.validator_value or []
            instance = error.instance if isinstance(error.instance, Mapping) else {}
            for name in required:
                if name not in instance:
                    violations.append(
                        SpecViolation(
                            _format_path([*base, name]),
                            f"required field {name!r} is missing — the frozen "
                            "ChartSpec vocabulary requires it here",
                        )
                    )
        elif error.validator == "enum":
            allowed = ", ".join(repr(v) for v in error.validator_value)
            violations.append(
                SpecViolation(
                    _format_path(base),
                    f"value {error.instance!r} is not one of the allowed values "
                    f"({allowed}) — this field is a closed vocabulary",
                )
            )
        elif error.validator == "const":
            violations.append(
                SpecViolation(
                    _format_path(base),
                    f"value {error.instance!r} must be exactly "
                    f"{error.validator_value!r} in the frozen ChartSpec vocabulary",
                )
            )
        else:
            violations.append(
                SpecViolation(
                    _format_path(base) or "<root>",
                    f"schema violation ({error.validator}): {error.message}",
                )
            )
    return violations


# ---------------------------------------------------------------------------
# Semantic validation: cross-check the spec against the dataset manifest
# ---------------------------------------------------------------------------


def _coverage_ce(entry: Mapping[str, Any]) -> tuple[float, float] | None:
    """A dataset's parsed usable extent expressed in CE years (review #52).

    BP coverages convert via ``year_ce = present_ce - age_bp``. Returns
    None when the coverage/time-axis block is not shaped as expected (a
    guard — the manifest validator owns shape enforcement)."""
    coverage = entry.get("coverage") or {}
    time_axis = entry.get("time_axis") or {}
    unit = time_axis.get("unit")
    try:
        if unit == "year_ce":
            return float(coverage["first_year_ce"]), float(coverage["last_year_ce"])
        if unit == "years_bp":
            present = float(time_axis["present_ce"])
            return present - float(coverage["oldest_bp"]), present - float(coverage["youngest_bp"])
    except (KeyError, TypeError, ValueError):
        return None
    return None


def _series_datasets(series: Mapping[str, Any]) -> list[str]:
    """The dataset ids a series plots (its ``dataset`` or its splice pair)."""
    if "dataset" in series:
        return [series["dataset"]]
    splice = series.get("splice_series")
    return list(splice) if isinstance(splice, Sequence) and not isinstance(splice, str) else []


def _series_coverage_ce(
    series: Mapping[str, Any], datasets: Mapping[str, Any]
) -> tuple[float, float] | None:
    """CE coverage extent for a series: a dataset's, or the *union* of a
    splice pair's members (review #52)."""
    extents = []
    for ds_id in _series_datasets(series):
        entry = datasets.get(ds_id)
        if not entry:
            return None
        extent = _coverage_ce(entry)
        if extent is None:
            return None
        extents.append(extent)
    if not extents:
        return None
    return min(e[0] for e in extents), max(e[1] for e in extents)


def _series_has_bp(series: Mapping[str, Any], datasets: Mapping[str, Any]) -> bool:
    for ds_id in _series_datasets(series):
        entry = datasets.get(ds_id)
        if entry and (entry.get("time_axis") or {}).get("unit") == "years_bp":
            return True
    return False


def _expected_units(
    series: Mapping[str, Any], datasets: Mapping[str, Any]
) -> tuple[set[str], str | None]:
    """The units a series' declared ``unit`` may legally take.

    Returns ``(units, converted_to)``: when a ``unit_conversion`` transform
    is present the only legal unit is its ``to_unit``; otherwise it is the
    source dataset(s)' ``variable.unit``."""
    converted_to: str | None = None
    for transform in series.get("transforms") or []:
        if isinstance(transform, Mapping) and transform.get("op") == "unit_conversion":
            converted_to = transform.get("to_unit")
    if converted_to is not None:
        return {converted_to}, converted_to
    units: set[str] = set()
    for ds_id in _series_datasets(series):
        entry = datasets.get(ds_id)
        if entry:
            unit = (entry.get("variable") or {}).get("unit")
            if unit is not None:
                units.add(unit)
    return units, None


def validate_spec(
    spec: Mapping[str, Any],
    manifest: Mapping[str, Any],
    data_extents: Mapping[str, tuple[float, float]] | None = None,
) -> None:
    """Validate one ChartSpec against the schema and the dataset manifest.

    Returns ``None`` for a valid spec; raises :class:`ChartSpecError`
    carrying **every** violation found otherwise. Pure code — the ADR-020
    guarantee that chart legality is decided by code, never the model.

    ``manifest`` is the raw ``datasets/manifest.yaml`` mapping (``datasets``
    keyed by id with ``time_axis``/``variable``/``coverage``;
    ``splice_pairs`` with ``overlap`` and ``rebaseline`` blocks).

    ``data_extents`` maps series id → ``(min, max)`` of that series' plotted
    values (post-transform, within the spec's time range), computed by the
    caller from the loaded frames. When ``None`` (planner-time structural
    validation, before any data is loaded) the extent-containment check is
    skipped; the render path (#17) MUST re-validate with extents before
    producing an artefact.

    Checks, beyond schema shape (each refusal names its spec path):

    - every referenced dataset id exists in ``manifest.datasets`` and is in
      the chart pack (``in_chart_pack``; review finding #117 — provisional
      datasets refuse by name, naming the pending confirmation issue #23);
    - ``series[*].unit`` equals the dataset's ``variable.unit`` (or the
      ``to_unit`` of a ``unit_conversion`` transform on that series);
    - ``splice_pair_id`` names a manifest ``splice_pairs`` entry whose
      members are both in the chart pack; ``splice_series`` equals exactly
      ``[pair.paleo, pair.instrumental]``; the mandatory
      ``annotations.splice_point`` / ``resolution_note`` are present and the
      splice year equals the pair's ``splice_year_ce``;
    - ``overlap_policy`` is present on every spliced series and equals the
      pair's manifest ``overlap.policy`` (review finding #47);
    - ``rebaseline_to`` presence matches the pair's manifest ``rebaseline``;
      ``apply_to`` and ``alignment_period_ce`` equal the manifest values;
      ``alignment_disclosure`` equals the manifest ``rebaseline.disclosure``
      verbatim (review finding #50);
    - time ranges lie within each series' dataset coverage — for a splice,
      within the union of the members' coverage (review finding #52). A
      series over a ``years_bp`` dataset in a CE-ranged spec without
      ``time_axis.convert_bp: true`` is a coverage-unit mismatch, refused at
      ``time_axis``;
    - ``scale_domain``: required per series for ``context_recent_inset``;
      when ``data_extents`` is given, each domain must contain its series'
      extent (review finding #48); any domain that excludes zero requires
      the series' ``annotations.non_zero_baseline`` label;
    - ``uncertainty_band.source`` names one of the series' datasets;
    - panel-pair rules: ``panels`` present iff ``chart_type`` is
      ``context_recent_inset``; the recent range within the context range;
      ``shared_y_scale_with`` names an existing panel.

    Phase discipline (review finding #126): the semantic cross-checks
    assume a structurally valid spec, so any structural violation —
    including a non-object top-level spec — raises immediately with the
    structural refusals alone. The semantic phase never sees a mistyped
    subtree, so no raw ``TypeError``/``AttributeError`` can escape this
    function: every refusal is a :class:`ChartSpecError`.
    """
    structural = list(_structural_violations(spec))
    if structural or not isinstance(spec, Mapping):
        _raise_violations(
            structural
            or [
                SpecViolation(
                    "<root>",
                    f"a ChartSpec must be a JSON object, not {type(spec).__name__}",
                )
            ]
        )
    violations: list[SpecViolation] = []

    datasets = manifest.get("datasets") or {}
    pairs = {p.get("id"): p for p in (manifest.get("splice_pairs") or []) if isinstance(p, Mapping)}
    chart_type = spec.get("chart_type")
    time_axis = spec.get("time_axis") or {}
    convert_bp = time_axis.get("convert_bp") is True
    series_list = spec.get("series") if isinstance(spec.get("series"), list) else []

    time_axis_flagged = False

    def add(path: str, reason: str) -> None:
        violations.append(SpecViolation(path, reason))

    def flag_time_axis(reason: str) -> None:
        nonlocal time_axis_flagged
        if not time_axis_flagged:
            add("time_axis", reason)
            time_axis_flagged = True

    for index, series in enumerate(series_list):
        if not isinstance(series, Mapping):
            continue
        prefix = f"series[{index}]"
        has_dataset = "dataset" in series
        has_splice = "splice_series" in series or "splice_pair_id" in series

        # Exactly one data source (dataset XOR splice pair).
        if has_dataset and has_splice:
            add(
                f"{prefix}.dataset",
                "a series carries exactly one data source: either a single "
                "'dataset' or a 'splice_series'/'splice_pair_id' pair, never both",
            )
        elif not has_dataset and not has_splice:
            add(
                f"{prefix}.dataset",
                "a series must name a data source: a single 'dataset' or a "
                "'splice_series'/'splice_pair_id' pair",
            )

        dataset_ok = False
        # --- plain-dataset series ------------------------------------
        if has_dataset and not has_splice:
            try:
                pack.require_in_chart_pack(manifest, series["dataset"])
                dataset_ok = True
            except ValueError as exc:
                add(f"{prefix}.dataset", str(exc))

        pair = None
        # --- splice-only fields on unspliced series (review #127) ----
        # Rebaselining, overlap policy and the splice annotations exist
        # only as manifest splice-pair decisions (ADR-020, amendments
        # 1-2, review #47). On a series without a splice pair they are
        # either an LLM-chosen alignment (the cherry-pick the curation
        # rule refuses) or a false disclosure baked into the artefact.
        if not has_splice:
            if "rebaseline_to" in series:
                add(
                    f"{prefix}.rebaseline_to",
                    "rebaseline_to is only legal on a spliced series whose manifest "
                    "splice pair records the alignment — rebaselining is a "
                    "curation-time decision fixed in the dataset manifest, never an "
                    "LLM choice on a plain series (ADR-020, review finding #127)",
                )
            if "overlap_policy" in series:
                add(
                    f"{prefix}.overlap_policy",
                    "overlap_policy discloses what happened to overlapping splice "
                    "samples; on a series without a splice pair it would render a "
                    "disclosure for data that was never discarded (review finding "
                    "#127)",
                )
            annotations = series.get("annotations") or {}
            if "splice_point" in annotations:
                add(
                    f"{prefix}.annotations.splice_point",
                    "a splice_point annotation on a series without a splice pair "
                    "marks a splice that does not exist — a fake splice marker on "
                    "continuous data is the mirror image of the hidden-splice "
                    "attack DESIGN §3.7 annotates against (review finding #127)",
                )
            if "resolution_note" in annotations:
                add(
                    f"{prefix}.annotations.resolution_note",
                    "a resolution_note describes the resolution change across a "
                    "splice; on a series without a splice pair it asserts a "
                    "resolution change that does not exist (review finding #127)",
                )

        # --- spliced series ------------------------------------------
        if has_splice:
            pair_id = series.get("splice_pair_id")
            if pair_id not in pairs:
                add(
                    f"{prefix}.splice_pair_id",
                    f"splice_pair_id {pair_id!r} does not name any splice_pairs "
                    "entry in the dataset manifest (splicing is manifest-keyed, "
                    "ADR-020)",
                )
            else:
                pair = pairs[pair_id]
                try:
                    pack.require_renderable_splice_pair(manifest, pair_id)
                    dataset_ok = True
                except ValueError as exc:
                    add(f"{prefix}.splice_pair_id", str(exc))

                expected_members = [pair.get("paleo"), pair.get("instrumental")]
                if list(series.get("splice_series") or []) != expected_members:
                    add(
                        f"{prefix}.splice_series",
                        f"splice_series {series.get('splice_series')!r} must equal the "
                        f"manifest pair {pair_id!r} members "
                        f"[paleo, instrumental] = {expected_members!r}",
                    )

            annotations = series.get("annotations") or {}
            if "splice_point" not in annotations:
                add(
                    f"{prefix}.annotations.splice_point",
                    "a spliced series must carry annotations.splice_point (the "
                    "rendered splice marker) — an unannotated splice is the "
                    "hidden-smoothing attack surface (DESIGN §3.7)",
                )
            elif pair is not None:
                year = (annotations.get("splice_point") or {}).get("year_ce")
                manifest_year = pair.get("splice_year_ce")
                if year != manifest_year:
                    add(
                        f"{prefix}.annotations.splice_point.year_ce",
                        f"splice_point.year_ce {year!r} must equal the manifest "
                        f"pair {series.get('splice_pair_id')!r} splice_year_ce "
                        f"{manifest_year!r} (fixed at curation time, ADR-020)",
                    )
            if "resolution_note" not in annotations:
                add(
                    f"{prefix}.annotations.resolution_note",
                    "a spliced series must carry annotations.resolution_note "
                    "describing the resolution change across the splice (DESIGN §3.7)",
                )

            # overlap policy (review #47)
            if "overlap_policy" not in series:
                add(
                    f"{prefix}.overlap_policy",
                    "a spliced series must declare overlap_policy: silence about "
                    "what happens to overlapping source samples is the residual "
                    "'hidden the decline' attack (review finding #47)",
                )
            elif pair is not None and series["overlap_policy"] in OVERLAP_POLICIES:
                manifest_policy = (pair.get("overlap") or {}).get("policy")
                if manifest_policy is not None and series["overlap_policy"] != manifest_policy:
                    add(
                        f"{prefix}.overlap_policy",
                        f"overlap_policy {series['overlap_policy']!r} must equal the "
                        f"manifest pair {series.get('splice_pair_id')!r} overlap.policy "
                        f"{manifest_policy!r} — the LLM cannot re-decide a curation call",
                    )

            # rebaseline (ADR-020 / review #50)
            if pair is not None:
                manifest_rebaseline = pair.get("rebaseline")
                has_rebaseline_to = "rebaseline_to" in series
                if manifest_rebaseline and not has_rebaseline_to:
                    add(
                        f"{prefix}.rebaseline_to",
                        f"the manifest pair {series.get('splice_pair_id')!r} defines a "
                        "rebaseline, so this series must carry a matching rebaseline_to",
                    )
                elif not manifest_rebaseline and has_rebaseline_to:
                    add(
                        f"{prefix}.rebaseline_to",
                        f"the manifest pair {series.get('splice_pair_id')!r} records no "
                        "rebaseline (rebaseline: null), so this series must not carry "
                        "rebaseline_to",
                    )
                elif manifest_rebaseline and has_rebaseline_to:
                    rb = series["rebaseline_to"] or {}
                    if rb.get("apply_to") != manifest_rebaseline.get("apply_to"):
                        add(
                            f"{prefix}.rebaseline_to.apply_to",
                            f"rebaseline_to.apply_to {rb.get('apply_to')!r} must equal "
                            f"the manifest-fixed member {manifest_rebaseline.get('apply_to')!r}"
                            " — shifting the wrong series moves a reconstruction off its "
                            "native reference",
                        )
                    elif rb.get("apply_to") not in _series_datasets(series):
                        # Defence in depth (review #127): even a manifest
                        # rebaseline entry cannot authorise shifting a
                        # dataset that is not a member of this series'
                        # splice pair.
                        add(
                            f"{prefix}.rebaseline_to.apply_to",
                            f"rebaseline_to.apply_to {rb.get('apply_to')!r} must name a "
                            f"member of this series' splice pair "
                            f"{_series_datasets(series)!r} — a rebaseline can only "
                            "shift a plotted splice member (review finding #127)",
                        )
                    if list(rb.get("alignment_period_ce") or []) != list(
                        manifest_rebaseline.get("alignment_period_ce") or []
                    ):
                        add(
                            f"{prefix}.rebaseline_to.alignment_period_ce",
                            f"alignment_period_ce {rb.get('alignment_period_ce')!r} must "
                            f"equal the manifest-fixed period "
                            f"{list(manifest_rebaseline.get('alignment_period_ce') or [])!r} "
                            "— the alignment period is a curation-time decision, never the "
                            "LLM's (ADR-020)",
                        )
                    disclosure = rb.get("alignment_disclosure")
                    manifest_disclosure = manifest_rebaseline.get("disclosure")
                    if (
                        disclosure is not None
                        and manifest_disclosure is not None
                        and disclosure != manifest_disclosure
                    ):
                        add(
                            f"{prefix}.rebaseline_to.alignment_disclosure",
                            "alignment_disclosure must equal the manifest "
                            "rebaseline.disclosure verbatim so the alignment method on "
                            "the artefact cannot drift from the curation record "
                            "(review finding #50)",
                        )

        # --- unit label matches source (or its conversion) -----------
        if dataset_ok and "unit" in series:
            allowed_units, converted_to = _expected_units(series, datasets)
            if allowed_units and series["unit"] not in allowed_units:
                if converted_to is not None:
                    reason = (
                        f"series unit {series['unit']!r} must equal the "
                        f"unit_conversion to_unit {converted_to!r} — a mismatch is a "
                        "mislabelled axis"
                    )
                else:
                    expected = ", ".join(repr(u) for u in sorted(allowed_units))
                    reason = (
                        f"series unit {series['unit']!r} must equal the dataset "
                        f"variable unit ({expected}) — a mismatch is a mislabelled axis"
                    )
                add(f"{prefix}.unit", reason)

        # --- uncertainty band source is a series member --------------
        if "uncertainty_band" in series:
            source = (series["uncertainty_band"] or {}).get("source")
            members = _series_datasets(series)
            if source not in members:
                add(
                    f"{prefix}.uncertainty_band.source",
                    f"uncertainty_band.source {source!r} must be one of this series' "
                    f"datasets {members!r} — a band attaches to a splice member "
                    "(amendment 6)",
                )

        # --- scale-domain integrity (review #48) ---------------------
        if chart_type == "context_recent_inset" and "scale_domain" not in series:
            add(
                f"{prefix}.scale_domain",
                "context_recent_inset requires an explicit scale_domain on every "
                "series — shared per-axis domains across panels cannot be implicit "
                "(amendment 5)",
            )
        domain = series.get("scale_domain")
        annotations = series.get("annotations") or {}
        excludes_zero = False
        if isinstance(domain, Sequence) and not isinstance(domain, str) and len(domain) == 2:
            low, high = domain[0], domain[1]
            excludes_zero = low > 0 or high < 0
            if excludes_zero and "non_zero_baseline" not in annotations:
                add(
                    f"{prefix}.annotations.non_zero_baseline",
                    f"scale_domain {list(domain)!r} excludes zero, so the series must "
                    "carry annotations.non_zero_baseline naming the truncated axis "
                    "(review finding #48; §3.7 per-axis rule)",
                )
            if data_extents is not None and series.get("id") in data_extents:
                emin, emax = data_extents[series["id"]]
                if emin < low or emax > high:
                    add(
                        f"{prefix}.scale_domain",
                        f"scale_domain {list(domain)!r} does not contain the plotted "
                        f"extent ({emin}, {emax}) — clipping or flattening the data by "
                        "the axis window is cherry-picking (review finding #48)",
                    )
        if "non_zero_baseline" in annotations and not excludes_zero:
            add(
                f"{prefix}.annotations.non_zero_baseline",
                "annotations.non_zero_baseline asserts a zero-excluding axis, but "
                "this series' scale_domain does not exclude zero (or is absent) — "
                "a false truncation disclosure (review finding #127); the validator "
                "owns this rule, not the renderer",
            )

        # --- coverage-unit gate (review #52 / amendment 8) -----------
        if _series_has_bp(series, datasets) and not convert_bp:
            flag_time_axis(
                "a series over a years_bp dataset needs time_axis.convert_bp: true; "
                "without it the spec's CE ranges cannot be compared against BP coverage "
                "at all (amendment 8)",
            )

    # --- time-range coverage containment (review #52) ----------------
    def _check_range_within_coverage(range_path: str, time_range: Any) -> None:
        if not (
            isinstance(time_range, Sequence)
            and not isinstance(time_range, str)
            and len(time_range) == 2
        ):
            return
        start, end = time_range[0], time_range[1]
        for series in series_list:
            if not isinstance(series, Mapping):
                continue
            if _series_has_bp(series, datasets) and not convert_bp:
                continue
            extent = _series_coverage_ce(series, datasets)
            if extent is None:
                continue
            cov_min, cov_max = extent
            for ds_id in _series_datasets(series):
                if start < cov_min:
                    add(
                        range_path,
                        f"{range_path} start {start!r} is before dataset {ds_id!r} "
                        f"coverage start {cov_min!r} (coverage is the parsed usable "
                        "extent, review finding #52)",
                    )
                    break
                if end > cov_max:
                    add(
                        range_path,
                        f"{range_path} end {end!r} is after dataset {ds_id!r} coverage "
                        f"end {cov_max!r} (coverage is the parsed usable extent, "
                        "review finding #52)",
                    )
                    break

    # --- panel-pair rules (amendments 4-5) + range containment -------
    panels = spec.get("panels")
    if chart_type == "context_recent_inset":
        if panels is None:
            add(
                "panels",
                "context_recent_inset requires a panels block with a context and a "
                "recent panel (amendment 4)",
            )
        elif isinstance(panels, Mapping):
            context = panels.get("context") if isinstance(panels.get("context"), Mapping) else {}
            recent = panels.get("recent") if isinstance(panels.get("recent"), Mapping) else {}
            recent_range = recent.get("time_range_ce")
            context_range = context.get("time_range_ce")
            if (
                isinstance(recent_range, Sequence)
                and not isinstance(recent_range, str)
                and len(recent_range) == 2
                and isinstance(context_range, Sequence)
                and not isinstance(context_range, str)
                and len(context_range) == 2
                and (recent_range[0] < context_range[0] or recent_range[1] > context_range[1])
            ):
                add(
                    "panels.recent.time_range_ce",
                    f"the recent panel range {list(recent_range)!r} must lie within the "
                    f"context panel range {list(context_range)!r} (the inset is a zoom "
                    "of the context, amendment 4)",
                )
            for panel_name in ("context", "recent"):
                panel = panels.get(panel_name)
                if not isinstance(panel, Mapping):
                    continue
                if "shared_y_scale_with" in panel and panel["shared_y_scale_with"] not in (
                    "context",
                    "recent",
                ):
                    add(
                        f"panels.{panel_name}.shared_y_scale_with",
                        f"shared_y_scale_with {panel['shared_y_scale_with']!r} must name "
                        "an existing panel (context or recent)",
                    )
                _check_range_within_coverage(
                    f"panels.{panel_name}.time_range_ce", panel.get("time_range_ce")
                )
    else:
        if panels is not None:
            add(
                "panels",
                f"panels is only valid for chart_type 'context_recent_inset', not "
                f"{chart_type!r} — the panel pair is that type's layout wrapper "
                "(amendment 4)",
            )
        if "time_range_ce" in spec:
            _check_range_within_coverage("time_range_ce", spec.get("time_range_ce"))

    if violations:
        _raise_violations(violations)
    return None


def _raise_violations(violations: list[SpecViolation]) -> None:
    """Raise :class:`ChartSpecError`, de-duplicating identical
    (path, reason) pairs (a BP series flagged for both panels would
    otherwise repeat) while preserving order."""
    seen: set[tuple[str, str]] = set()
    unique: list[SpecViolation] = []
    for violation in violations:
        key = (violation.path, violation.reason)
        if key not in seen:
            seen.add(key)
            unique.append(violation)
    raise ChartSpecError(unique)


# ---------------------------------------------------------------------------
# Canonical spec hashing (for /chart/<hash> permalinks)
# ---------------------------------------------------------------------------


def _canonicalize(value: Any) -> Any:
    """Recursively canonicalise for hashing: integer-valued floats collapse
    to ints (``1959.0`` == ``1959``); dicts/lists rebuilt structurally.

    ``bool`` is preserved (it is an ``int`` subclass but not a number here)."""
    if isinstance(value, bool):
        return value
    if isinstance(value, float):
        return int(value) if value.is_integer() else value
    if isinstance(value, Mapping):
        return {key: _canonicalize(val) for key, val in value.items()}
    if isinstance(value, (list, tuple)):
        return [_canonicalize(item) for item in value]
    return value


def spec_hash(spec: Mapping[str, Any]) -> str:
    """Canonical content hash of a ChartSpec, for ``/chart/<hash>`` permalinks.

    Returns a 64-char lowercase hex sha256 over a canonical serialisation.
    Contract (pinned by tests):

    - key order never matters (deep canonicalisation, sorted keys);
    - the top-level ``_meta`` block is excluded (provenance/sign-off notes
      are not chart semantics);
    - numbers are canonicalised so ``1959`` and ``1959.0`` hash identically
      (migration-safe: a serialiser that floats an int must not move every
      permalink);
    - any semantic change — title, ranges, domains, spec_version, series —
      changes the hash.

    Pure and deterministic across processes and platforms.
    """
    payload = {key: value for key, value in spec.items() if key != "_meta"}
    canonical = _canonicalize(payload)
    serialised = json.dumps(canonical, sort_keys=True, separators=(",", ":"), ensure_ascii=False)
    return hashlib.sha256(serialised.encode("utf-8")).hexdigest()


# ---------------------------------------------------------------------------
# In-repo schema documentation for the planner prompt (#16)
# ---------------------------------------------------------------------------


def render_schema_doc() -> str:
    """The in-repo ChartSpec doc for the planner prompt (#16), as Markdown.

    Deterministically derived from :func:`chartspec_schema` so the doc
    cannot drift from the schema: the committed ``charts/CHARTSPEC.md``
    must equal this function's output byte-for-byte (pinned by
    ``test_schema_doc_matches_schema``), and the text names every chart
    type, transform op and overlap policy plus the load-bearing field
    names. Ends with a newline (end-of-file hook).
    """
    chart_types = ", ".join(f"`{name}`" for name in sorted(CHART_TYPES))
    transform_ops = ", ".join(f"`{name}`" for name in sorted(TRANSFORM_OPS))
    overlap_policies = ", ".join(f"`{name}`" for name in sorted(OVERLAP_POLICIES))

    lines = [
        "# ChartSpec vocabulary (issue #15)",
        "",
        "> Generated from `charts.spec.chartspec_schema()` by",
        "> `charts.spec.render_schema_doc()`. Do not edit by hand — the test",
        "> `test_schema_doc_matches_schema` pins this file byte-for-byte to the",
        "> schema, so it can never drift from what the validator enforces.",
        "",
        "The chart planner (#16) emits a **ChartSpec** — a JSON document, never",
        "code. `charts.spec.validate_spec` decides legality in pure code and",
        "cross-checks every curation-time decision against `datasets/manifest.yaml`",
        "(ADR-020): the model supplies neither numbers, pixels, nor artefact text.",
        "The schema is closed everywhere (`additionalProperties: false`); the only",
        "tolerated extra is a top-level `_meta` provenance block, which is ignored",
        "semantically and excluded from the permalink hash.",
        "",
        "## Closed vocabularies",
        "",
        f"- **chart_type** — one of: {chart_types}. The five MVP types are a closed",
        "  enum; warming stripes and other Phase 2 types are not expressible.",
        f"- **transforms[*].op** — one of: {transform_ops}. These generic transforms",
        "  live in a per-series `transforms` list. A `unit_conversion` carries only",
        "  `to_unit`; the conversion arithmetic is code-owned (no LLM-authored",
        "  factor).",
        f"- **overlap_policy** — one of: {overlap_policies}. What a spec may carry for",
        "  a given splice is further narrowed to the manifest-legal value recorded in",
        "  that pair's `overlap.policy` (review finding #47).",
        "",
        "## Top-level fields",
        "",
        "- **spec_version**, **chart_id**, **chart_type**, **title** — required.",
        "  **subtitle** is optional.",
        "- **time_range_ce** `[start, end]` — CE years for a single-panel chart; must",
        "  lie within every series' dataset coverage (the parsed usable extent,",
        "  review finding #52).",
        '- **time_axis** `{calendar: "CE", convert_bp: <bool>}` — set `convert_bp:',
        "  true` when any series plots a `years_bp` dataset on the CE axis. BCE-aware",
        "  axis labelling is renderer-owned time_axis semantics (amendment 8); there",
        "  is no per-spec label/tick styling field.",
        "- **panels** — present if and only if `chart_type` is `context_recent_inset`.",
        "  A `context` and a `recent` panel, each with a `label` and a",
        "  `time_range_ce`; the recent range must lie within the context range, and",
        "  `shared_y_scale_with` names the other panel (amendments 4-5).",
        "- **series** — one or more series (see below).",
        "",
        "## Series fields",
        "",
        "A series names exactly one data source: a single `dataset`, or a splice",
        "pair (`splice_series` + `splice_pair_id`). Both must resolve to chart-pack",
        "datasets (`in_chart_pack`, review finding #117).",
        "",
        "- **id**, **label**, **unit** — required. `unit` must equal the source",
        "  dataset's variable unit (or a `unit_conversion` transform's `to_unit`).",
        "- **axis** `left|right`, **color** — optional per-series presentation.",
        "- **dataset** — a single chart-pack dataset id.",
        "- **splice_series** `[paleo, instrumental]` + **splice_pair_id** — a",
        "  manifest-keyed splice. `splice_series` must equal the pair's",
        "  `[paleo, instrumental]`; the splice year, resolution note and rebaseline",
        "  legality are all owned by the manifest pair (ADR-020).",
        "- **overlap_policy** — required on a spliced series; must equal the pair's",
        "  manifest `overlap.policy` (review finding #47).",
        "- **rebaseline_to** `{apply_to, alignment_period_ce, alignment_disclosure}` —",
        "  present if and only if the manifest pair records a rebaseline. `apply_to`",
        "  and `alignment_period_ce` must equal the manifest values; the",
        "  `alignment_disclosure` string must equal the manifest",
        "  `rebaseline.disclosure` verbatim, so the alignment method reaches the",
        "  artefact and cannot drift (review finding #50).",
        "- **scale_domain** `[min, max]` — required per series for",
        "  `context_recent_inset` (shared per-axis domains across panels). It must",
        "  contain the plotted data's extent (no clipping, review finding #48); any",
        "  domain that excludes zero requires the `non_zero_baseline` annotation.",
        "- **uncertainty_band** `{lower, upper, source}` — `source` names a member",
        "  dataset of this series (amendment 6).",
        "- **baseline** `{value, label}` — an optional zero/reference line label.",
        "- **transforms** — a list of generic transform ops (see above).",
        "- **annotations** `{splice_point, resolution_note, non_zero_baseline}` — a",
        "  spliced series must carry `splice_point` (with the splice `year_ce`) and",
        "  `resolution_note`. Annotation placement is fixed semantics, not a spec",
        "  choice (amendment 7).",
        "",
        "## Captions",
        "",
        "There is no `caption` field anywhere. Captions (sources, licences, access",
        "date, site URL) are generated by the renderer from the manifest",
        "attribution/licence strings and deployment config, so they cannot drift",
        "from the licensing record and cannot be an injection vector (amendment 9).",
    ]
    # Exactly one trailing newline (end-of-file hook; byte-equality with the
    # committed charts/CHARTSPEC.md).
    return "\n".join(lines) + "\n"
