"""ChartSpec: JSON Schema, pure-code validator and canonical spec hashing (issue #15).

This module freezes the chart vocabulary (DESIGN §3.7 as amended; ADR-020;
the ten binding vocabulary amendments filed on issue #15 from the #4 spike;
review findings #47/#48/#50/#52). The LLM chart planner (#16) writes a
ChartSpec — never code — and everything here is pure: no network, no
filesystem reach-around, no data loading (IMPLEMENTATION.md §1).

RED phase: the public functions below are contract stubs raising
:class:`NotImplementedError`. The failing tests in
``tests/unit/test_chartspec.py`` and ``tests/unit/test_chartspec_hashing.py``
pin the contracts; the implementer makes them pass without weakening them
(ORCHESTRATION.md) and then deletes this paragraph.

Vocabulary decisions frozen here
--------------------------------

- **Chart types** (:data:`CHART_TYPES`): the five MVP types. The
  context+recent-inset panel pair is a *layout wrapper* (vocabulary
  amendment 4): ``panels.context`` / ``panels.recent`` each carry a
  ``label`` and ``time_range_ce``; the series themselves carry
  ``axis: left|right`` and are drawn in both panels.
- **Transforms**: the generic four (:data:`TRANSFORM_OPS`) live in a
  per-series ``transforms`` list of ``{op: ..., <params>}`` objects; the
  three flagship transforms are dedicated fields with manifest-anchored
  semantics — ``splice_series`` + ``splice_pair_id`` (+ mandatory
  ``overlap_policy``), ``rebaseline_to`` and the spec-level ``time_axis``.
- **Manifest is the source of truth** (ADR-020): splice membership, splice
  year, overlap policy, rebaseline apply-to/alignment period and the
  alignment disclosure are curation-time decisions recorded in
  ``datasets/manifest.yaml``. The validator *cross-checks* the spec against
  the manifest and refuses any disagreement; it never re-decides them.
- **No caption in the spec**: captions (sources, licences, access date,
  site URL) are generated by the renderer from the manifest attribution /
  licence strings and deployment config (vocabulary amendment 9). Free
  caption text in an LLM-authored spec is a drift **and injection** vector,
  so the schema has no ``caption`` property at all.
- **Closed everywhere**: ``additionalProperties: false`` throughout (the
  only tolerated extra is the top-level ``_meta`` provenance block, which
  is semantically inert and excluded from hashing). Annotation *placement*
  is fixed semantics — splice rules render in every panel they intersect,
  text labels render once in the context panel (amendment 7) — so there is
  no placement field for a spec to author.
"""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any

#: The closed chart-type vocabulary (DESIGN §3.7 MVP list; warming stripes
#: is Phase 2 and deliberately NOT here).
CHART_TYPES = frozenset(
    {
        "line",
        "area",
        "bar",
        "dual_axis_line",
        "context_recent_inset",
    }
)

#: The closed generic-transform vocabulary (`transforms[*].op`). The three
#: flagship transforms (splice, rebaseline, BP→CE time axis) are dedicated
#: spec fields, not list entries, because their parameters are
#: manifest-anchored rather than LLM-choosable.
TRANSFORM_OPS = frozenset(
    {
        "resample",
        "anomaly_vs_baseline",
        "rolling_mean",
        "unit_conversion",
    }
)

#: The closed overlap-policy vocabulary (review finding #47). What a spec
#: may carry for a given pair is further narrowed to the *manifest-legal*
#: value recorded in that pair's ``overlap.policy`` — the curation-time
#: decision about what happens to overlapping source samples.
OVERLAP_POLICIES = frozenset(
    {
        "prefer_instrumental",
        "prefer_paleo",
        "show_both",
    }
)


@dataclass(frozen=True)
class SpecViolation:
    """One actionable refusal: the spec path that is wrong, and why.

    ``path`` is rooted at the spec document and uses dotted/bracketed
    syntax (``chart_type``, ``series[1].rebaseline_to.alignment_period_ce``,
    ``panels.recent.time_range_ce``). ``reason`` states what was found and
    what would be legal — never a bare "invalid".
    """

    path: str
    reason: str


class ChartSpecError(ValueError):
    """A refused ChartSpec. Carries every violation found (the validator

    collects; it does not stop at the first), and the exception message
    contains each violation's path so a log line alone is actionable
    (issue #15 acceptance: rejection messages name field + reason).
    """

    def __init__(self, violations: tuple[SpecViolation, ...] | list[SpecViolation]) -> None:
        self.violations: tuple[SpecViolation, ...] = tuple(violations)
        super().__init__("; ".join(f"{v.path}: {v.reason}" for v in self.violations))


def chartspec_schema() -> dict[str, Any]:
    """The ChartSpec JSON Schema (draft 2020-12) — the frozen vocabulary.

    Structural contract (pinned by tests):

    - ``chart_type`` enum is exactly :data:`CHART_TYPES`;
    - ``transforms[*].op`` enum is exactly :data:`TRANSFORM_OPS`;
    - ``overlap_policy`` enum is exactly :data:`OVERLAP_POLICIES`;
    - ``time_axis`` is ``{calendar: "CE" (const), convert_bp: bool}`` —
      BCE-aware axis labelling (negative years as "8000 BCE", no year-0
      tick) is *time_axis semantics* owned by the renderer, so there is no
      per-spec label-format/styling field (vocabulary amendment 8);
    - ``rebaseline_to`` requires ``apply_to``, ``alignment_period_ce`` and
      ``alignment_disclosure`` (review finding #50: the alignment method
      must reach the artefact, not only repo files);
    - a series carries exactly one data source: ``dataset`` XOR
      (``splice_series`` + ``splice_pair_id``);
    - ``uncertainty_band`` is ``{lower, upper, source: <dataset_id>}`` —
      bands attach to a splice *member* (amendment 6);
    - no ``caption`` property anywhere (amendment 9 — manifest-generated);
    - ``additionalProperties: false`` at every level; only the top-level
      ``_meta`` block is admitted (and ignored semantically).

    Pure; returns a plain dict, safe to serialise for the planner prompt.
    """
    raise NotImplementedError("issue #15 RED phase — implement to the failing tests")


def validate_spec(
    spec: Mapping[str, Any],
    manifest: Mapping[str, Any],
    data_extents: Mapping[str, tuple[float, float]] | None = None,
) -> None:
    """Validate one ChartSpec against the schema and the dataset manifest.

    Returns ``None`` for a valid spec; raises :class:`ChartSpecError`
    carrying **every** violation found otherwise. Pure code — the ADR-020
    guarantee that chart legality is decided by code, never the model.

    ``manifest`` is the raw ``datasets/manifest.yaml`` mapping (``datasets``
    keyed by id with ``time_axis``/``variable``/``coverage``;
    ``splice_pairs`` with ``overlap`` and ``rebaseline`` blocks).

    ``data_extents`` maps series id → ``(min, max)`` of that series' plotted
    values (post-transform, within the spec's time range), computed by the
    caller from the loaded frames. When ``None`` (planner-time structural
    validation, before any data is loaded) the extent-containment check is
    skipped; the render path (#17) MUST re-validate with extents before
    producing an artefact.

    Checks, beyond schema shape (each refusal names its spec path):

    - every referenced dataset id exists in ``manifest.datasets``;
    - ``series[*].unit`` equals the dataset's ``variable.unit`` (or the
      ``to_unit`` of a ``unit_conversion`` transform on that series) —
      a unit mismatch is a mislabelled axis;
    - ``splice_pair_id`` names a manifest ``splice_pairs`` entry;
      ``splice_series`` equals exactly ``[pair.paleo, pair.instrumental]``;
      the mandatory ``annotations.splice_point`` / ``resolution_note`` are
      present and the splice year equals the pair's ``splice_year_ce``;
    - ``overlap_policy`` is present on every spliced series and equals the
      pair's manifest ``overlap.policy`` (review finding #47 — silently
      discarding overlapping samples is the residual "hidden the decline"
      attack; the policy is explicit, manifest-legal and disclosed);
    - ``rebaseline_to`` presence matches the pair's manifest ``rebaseline``
      (present iff the manifest records one); ``apply_to`` and
      ``alignment_period_ce`` equal the manifest values (an LLM-chosen
      alignment period is refused by name); ``alignment_disclosure``
      equals the manifest ``rebaseline.disclosure`` string verbatim
      (review finding #50 — the disclosure reaches the artefact and cannot
      drift from the curation record);
    - time ranges (top-level ``time_range_ce``, or every panel's
      ``time_range_ce``) lie within each series' dataset coverage — for a
      splice, within the union of the members' coverage — using coverage
      as *parsed usable extent* (review finding #52). BP coverages convert
      via ``year_ce = present_ce - age_bp``; a series over a ``years_bp``
      dataset in a CE-ranged spec without ``time_axis.convert_bp: true``
      is a coverage-unit mismatch and refused at ``time_axis``;
    - ``scale_domain``: required per series for ``context_recent_inset``
      (amendment 5 — shared per-axis domains across panels must be
      explicit); when ``data_extents`` is given, each domain must contain
      its series' extent (clipping or flattening by axis window is
      cherry-picking, review finding #48); any domain that excludes zero —
      on ANY axis, anomaly or absolute alike — requires the series'
      ``annotations.non_zero_baseline`` label (§3.7 per-axis rule as
      amended by #48; the flagship CO₂ axis is the precedent);
    - ``uncertainty_band.source`` names one of the series' datasets;
    - panel-pair rules: ``panels`` present iff ``chart_type`` is
      ``context_recent_inset``; both ``context`` and ``recent`` present;
      the recent range within the context range;
      ``shared_y_scale_with`` names an existing panel.
    """
    raise NotImplementedError("issue #15 RED phase — implement to the failing tests")


def spec_hash(spec: Mapping[str, Any]) -> str:
    """Canonical content hash of a ChartSpec, for ``/chart/<hash>`` permalinks.

    Returns a 64-char lowercase hex sha256 over a canonical serialisation.
    Contract (pinned by tests):

    - key order never matters (deep canonicalisation, sorted keys);
    - the top-level ``_meta`` block is excluded (provenance/sign-off notes
      are not chart semantics);
    - numbers are canonicalised so ``1959`` and ``1959.0`` hash identically
      (migration-safe: a serialiser that floats an int must not move every
      permalink);
    - any semantic change — title, ranges, domains, spec_version, series —
      changes the hash.

    Pure and deterministic across processes and platforms.
    """
    raise NotImplementedError("issue #15 RED phase — implement to the failing tests")


def render_schema_doc() -> str:
    """The in-repo ChartSpec doc for the planner prompt (#16), as Markdown.

    Deterministically derived from :func:`chartspec_schema` so the doc
    cannot drift from the schema: the committed ``charts/CHARTSPEC.md``
    must equal this function's output byte-for-byte (pinned by
    ``test_schema_doc_matches_schema``), and the text names every chart
    type, transform op and overlap policy plus the load-bearing field
    names. Ends with a newline (end-of-file hook).
    """
    raise NotImplementedError("issue #15 RED phase — implement to the failing tests")
