"""ChartSpec: JSON Schema, pure-code validator and canonical spec hashing (issue #15).

This module freezes the chart vocabulary (DESIGN §3.7 as amended; ADR-020;
the ten binding vocabulary amendments filed on issue #15 from the #4 spike;
review findings #47/#48/#50/#52). The LLM chart planner (#16) writes a
ChartSpec — never code — and everything here is pure: no network, no
filesystem reach-around, no data loading (IMPLEMENTATION.md §1).

Vocabulary decisions frozen here
--------------------------------

- **Chart types** (:data:`CHART_TYPES`): the five MVP types. The
  context+recent-inset panel pair is a *layout wrapper* (vocabulary
  amendment 4): ``panels.context`` / ``panels.recent`` each carry a
  ``label`` and ``time_range_ce``; the series themselves carry
  ``axis: left|right`` and are drawn in both panels.
- **Transforms**: the generic four (:data:`TRANSFORM_OPS`) live in a
  per-series ``transforms`` list of ``{op: ..., <params>}`` objects; the
  three flagship transforms are dedicated fields with manifest-anchored
  semantics — ``splice_series`` + ``splice_pair_id`` (+ mandatory
  ``overlap_policy``), ``rebaseline_to`` and the spec-level ``time_axis``.
- **Manifest is the source of truth** (ADR-020): splice membership, splice
  year, overlap policy, rebaseline apply-to/alignment period and the
  alignment disclosure are curation-time decisions recorded in
  ``datasets/manifest.yaml``. The validator *cross-checks* the spec against
  the manifest and refuses any disagreement; it never re-decides them.
- **No caption in the spec**: captions (sources, licences, access date,
  site URL) are generated by the renderer from the manifest attribution /
  licence strings and deployment config (vocabulary amendment 9). Free
  caption text in an LLM-authored spec is a drift **and injection** vector,
  so the schema has no ``caption`` property at all.
- **Closed everywhere**: ``additionalProperties: false`` throughout (the
  only tolerated extra is the top-level ``_meta`` provenance block, which
  is semantically inert and excluded from hashing). Annotation *placement*
  is fixed semantics — splice rules render in every panel they intersect,
  text labels render once in the context panel (amendment 7) — so there is
  no placement field for a spec to author.
"""

from __future__ import annotations

import hashlib
import json
import math
import re
from collections.abc import Mapping, Sequence
from dataclasses import dataclass, field
from typing import Any

from jsonschema import Draft202012Validator

from charts import pack

#: The closed chart-type vocabulary (DESIGN §3.7 MVP list; warming stripes
#: is Phase 2 and deliberately NOT here).
CHART_TYPES = frozenset(
    {
        "line",
        "area",
        "bar",
        "dual_axis_line",
        "context_recent_inset",
    }
)

#: The closed generic-transform vocabulary (`transforms[*].op`). The three
#: flagship transforms (splice, rebaseline, BP→CE time axis) are dedicated
#: spec fields, not list entries, because their parameters are
#: manifest-anchored rather than LLM-choosable.
TRANSFORM_OPS = frozenset(
    {
        "resample",
        "anomaly_vs_baseline",
        "rolling_mean",
        "unit_conversion",
    }
)

#: The closed overlap-policy vocabulary (review finding #47). What a spec
#: may carry for a given pair is further narrowed to the *manifest-legal*
#: value recorded in that pair's ``overlap.policy`` — the curation-time
#: decision about what happens to overlapping source samples.
OVERLAP_POLICIES = frozenset(
    {
        "prefer_instrumental",
        "prefer_paleo",
        "show_both",
    }
)

#: Flattening bound for LLM-authored axis domains (review finding #129).
#: A ``scale_domain`` must not span more than this factor times the
#: plotted data's span, *plus* a free allowance for extending the
#: zero-side edge to zero (zero-inclusion is the honest default for
#: absolute quantities, DESIGN §3.7). This is a chart-integrity default,
#: not renderer discretion. Calibration: the largest committed legal
#: ratio is the flagship temperature axis at 1.64x its extent span, and
#: zero-inclusion cases like [0, 120] over (10, 100) reach 1.33x after
#: the zero allowance — so 4x leaves every committed case at least 2x
#: headroom, while the flat-line attacks the finding names ([-30, 30]
#: over a (-0.7, 1.4) anomaly is ~29x; [-1e6, 1e6] over (10, 100) is
#: ~22000x) refuse by orders of magnitude.
SCALE_DOMAIN_MAX_SPAN_FACTOR = 4.0

#: The code-owned unit-conversion table (review finding #132): the only
#: legal ``(from_unit, to_unit)`` conversions, with their factors. This
#: is the single source of truth the renderer (#17) executes — the
#: validator refuses any ``unit_conversion`` not recorded here, so the
#: axis unit label can never become free LLM text. Entries are added by
#: code review as pack datasets need them, never by prompt engineering.
#: Anomaly conversions are pure scalings (no offset).
UNIT_CONVERSIONS: dict[tuple[str, str], float] = {
    ("Mt CO2/yr", "Gt CO2/yr"): 1e-3,
    ("degC_anomaly", "degF_anomaly"): 1.8,
}

#: Bounds for ``window_years`` on ``rolling_mean``/``resample`` (review
#: finding #132): strictly positive, at most 100 years. The coarsest
#: resolution in the curated pack is Kaufman's 100-year proxy bins, so a
#: window beyond a century smooths harder than anything the data
#: legitimises — a 5000-year rolling mean over the flagship is a
#: legal-looking smoothing attack the vocabulary otherwise polices.
MAX_WINDOW_YEARS = 100.0

#: Per-op parameter contracts (review finding #132): the params each
#: transform op requires — and the only ones it may carry.
TRANSFORM_PARAMS: dict[str, frozenset[str]] = {
    "resample": frozenset({"window_years"}),
    "rolling_mean": frozenset({"window_years"}),
    "anomaly_vs_baseline": frozenset(),
    "unit_conversion": frozenset({"to_unit"}),
}

#: Serialised-size ceilings (review finding #137). ADR-020's own design
#: expectation is a ~1 KB spec; the largest committed spec (the
#: flagship, _meta included) is ~3.2 KB. 8 KiB total gives 2.5x
#: headroom over the largest real spec while keeping the permalink
#: store and the SVG renderer bounded; 2 KiB bounds the semantically
#: inert _meta block (the flagship's provenance block is ~0.8 KB).
SPEC_MAX_BYTES = 8192
META_MAX_BYTES = 2048

#: Minimum span of the recent-inset panel, in years (review finding
#: #130). The context+recent panel pair is §3.7's honest answer to the
#: 10-kyr axis problem; a one-year (or narrower) inset is an
#: information-free sliver that degrades the pair to decoration. Ten
#: years is the narrowest window in which an annual-resolution series
#: shows any trend at all; every committed inset (flagship: 175 years,
#: synthetic fixtures: 100 years) clears it by an order of magnitude.
MIN_RECENT_PANEL_SPAN_YEARS = 10.0


@dataclass(frozen=True)
class SpecViolation:
    """One actionable refusal: the spec path that is wrong, and why.

    ``path`` is rooted at the spec document and uses dotted/bracketed
    syntax (``chart_type``, ``series[1].rebaseline_to.alignment_period_ce``,
    ``panels.recent.time_range_ce``). ``reason`` states what was found and
    what would be legal — never a bare "invalid".
    """

    path: str
    reason: str


class ChartSpecError(ValueError):
    """A refused ChartSpec. Carries every violation found (the validator

    collects; it does not stop at the first), and the exception message
    contains each violation's path so a log line alone is actionable
    (issue #15 acceptance: rejection messages name field + reason).
    """

    def __init__(self, violations: tuple[SpecViolation, ...] | list[SpecViolation]) -> None:
        self.violations: tuple[SpecViolation, ...] = tuple(violations)
        super().__init__("; ".join(f"{v.path}: {v.reason}" for v in self.violations))


# ---------------------------------------------------------------------------
# The frozen JSON Schema (draft 2020-12)
# ---------------------------------------------------------------------------


def chartspec_schema() -> dict[str, Any]:
    """The ChartSpec JSON Schema (draft 2020-12) — the frozen vocabulary.

    Structural contract (pinned by tests):

    - ``chart_type`` enum is exactly :data:`CHART_TYPES`;
    - ``transforms[*].op`` enum is exactly :data:`TRANSFORM_OPS`;
    - ``overlap_policy`` enum is exactly :data:`OVERLAP_POLICIES`;
    - ``time_axis`` is ``{calendar: "CE" (const), convert_bp: bool}`` —
      BCE-aware axis labelling (negative years as "8000 BCE", no year-0
      tick) is *time_axis semantics* owned by the renderer, so there is no
      per-spec label-format/styling field (vocabulary amendment 8);
    - ``rebaseline_to`` requires ``apply_to``, ``alignment_period_ce`` and
      ``alignment_disclosure`` (review finding #50: the alignment method
      must reach the artefact, not only repo files);
    - a series carries exactly one data source: ``dataset`` XOR
      (``splice_series`` + ``splice_pair_id``);
    - ``uncertainty_band`` is ``{lower, upper, source: <dataset_id>}`` —
      bands attach to a splice *member* (amendment 6);
    - no ``caption`` property anywhere (amendment 9 — manifest-generated);
    - ``additionalProperties: false`` at every level; only the top-level
      ``_meta`` block is admitted (and ignored semantically).

    Pure; returns a plain dict, safe to serialise for the planner prompt.
    """
    year_pair = {
        "type": "array",
        "items": {"type": "number"},
        "minItems": 2,
        "maxItems": 2,
    }
    # String bounds (review finding #137): generous but finite — the
    # validator's purpose is bounding inputs, and the permalink store
    # re-renders whatever validates, forever.
    short_text = {"type": "string", "maxLength": 200}
    long_text = {"type": "string", "maxLength": 500}
    identifier = {"type": "string", "maxLength": 64}
    unit_text = {"type": "string", "maxLength": 40}
    # A generic per-series transform. The conversion arithmetic is
    # code-owned: a unit_conversion carries only ``to_unit`` (never an
    # LLM-authored ``factor`` — that would be a silent scaling attack).
    transform = {
        "type": "object",
        "additionalProperties": False,
        "required": ["op"],
        "properties": {
            "op": {"enum": sorted(TRANSFORM_OPS)},
            "window_years": {"type": "number"},
            "to_unit": unit_text,
        },
    }
    splice_point = {
        "type": "object",
        "additionalProperties": False,
        "required": ["year_ce", "label"],
        "properties": {
            "year_ce": {"type": "number"},
            "label": short_text,
        },
    }
    non_zero_baseline = {
        "type": "object",
        "additionalProperties": False,
        "required": ["label"],
        "properties": {"label": short_text},
    }
    # Annotation *placement* is fixed semantics (amendment 7), so there is
    # no placement field: the only annotations a spec authors are the
    # splice point + resolution note (mandatory for a splice) and the
    # non-zero-baseline disclosure.
    annotations = {
        "type": "object",
        "additionalProperties": False,
        "properties": {
            "splice_point": splice_point,
            "resolution_note": long_text,
            "non_zero_baseline": non_zero_baseline,
        },
    }
    rebaseline_to = {
        "type": "object",
        "additionalProperties": False,
        "required": ["apply_to", "alignment_period_ce", "alignment_disclosure"],
        "properties": {
            "apply_to": identifier,
            "alignment_period_ce": year_pair,
            "alignment_disclosure": long_text,
        },
    }
    uncertainty_band = {
        "type": "object",
        "additionalProperties": False,
        "required": ["lower", "upper", "source"],
        "properties": {
            "lower": identifier,
            "upper": identifier,
            "source": identifier,
        },
    }
    baseline = {
        "type": "object",
        "additionalProperties": False,
        "required": ["value", "label"],
        "properties": {
            "value": {"type": "number"},
            "label": short_text,
        },
    }
    series = {
        "type": "object",
        "additionalProperties": False,
        "required": ["id", "label", "unit"],
        "properties": {
            "id": identifier,
            "label": short_text,
            "axis": {"enum": ["left", "right"]},
            "color": unit_text,
            "unit": unit_text,
            "dataset": identifier,
            "splice_series": {
                "type": "array",
                "items": identifier,
                "minItems": 2,
                "maxItems": 2,
            },
            "splice_pair_id": identifier,
            "overlap_policy": {"enum": sorted(OVERLAP_POLICIES)},
            "rebaseline_to": rebaseline_to,
            "scale_domain": year_pair,
            "baseline": baseline,
            "annotations": annotations,
            "uncertainty_band": uncertainty_band,
            "transforms": {"type": "array", "items": transform, "maxItems": 4},
        },
    }
    panel = {
        "type": "object",
        "additionalProperties": False,
        "required": ["label", "time_range_ce"],
        "properties": {
            "label": short_text,
            "time_range_ce": year_pair,
            "shared_y_scale_with": {"type": "string", "maxLength": 16},
        },
    }
    panels = {
        "type": "object",
        "additionalProperties": False,
        "required": ["context", "recent"],
        "properties": {
            "context": panel,
            "recent": panel,
        },
    }
    time_axis = {
        "type": "object",
        "additionalProperties": False,
        "required": ["calendar", "convert_bp"],
        "properties": {
            "calendar": {"const": "CE"},
            "convert_bp": {"type": "boolean"},
        },
    }
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "ChartSpec",
        "type": "object",
        "additionalProperties": False,
        "required": ["spec_version", "chart_id", "chart_type", "title", "series"],
        "properties": {
            "spec_version": {
                "type": "string",
                "pattern": r"^\d+\.\d+\.\d+$",
                "maxLength": 20,
            },
            "chart_id": {"type": "string", "pattern": "^[a-z0-9][a-z0-9-]{0,63}$"},
            "chart_type": {"enum": sorted(CHART_TYPES)},
            "title": short_text,
            "subtitle": short_text,
            "time_range_ce": year_pair,
            "time_axis": time_axis,
            "panels": panels,
            "series": {"type": "array", "items": series, "minItems": 1, "maxItems": 8},
            # Semantically inert provenance/sign-off block: admitted and
            # excluded from hashing, arbitrary content.
            "_meta": {"type": "object"},
        },
    }


# ---------------------------------------------------------------------------
# Parse seam: RFC 8259 only (review finding #128)
# ---------------------------------------------------------------------------


def _refuse_json_constant(token: str) -> Any:
    raise ChartSpecError(
        [
            SpecViolation(
                "<json>",
                f"non-finite JSON token {token!r} is not RFC 8259 JSON — NaN and "
                "Infinity silently disable the numeric integrity checks and are "
                "refused at parse time (review finding #128)",
            )
        ]
    )


def parse_spec_json(text: str) -> Any:
    """Parse ChartSpec JSON text, refusing the Python-dialect non-finite
    tokens (``NaN``, ``Infinity``, ``-Infinity``) that ``json.loads``
    otherwise accepts. The spec pipeline's parse seam (review #128):
    callers that receive spec *text* (permalink POSTs, replayed planner
    output) must come through here, so a non-RFC-8259 spec is refused
    before it can reach the validator as a special-comparison float.
    Raises :class:`ChartSpecError`; malformed JSON raises the usual
    ``json.JSONDecodeError`` (a transport error, not a spec refusal)."""
    return json.loads(text, parse_constant=_refuse_json_constant)


def _size_violations(spec: Any) -> list[SpecViolation]:
    """Serialised-size ceilings (review finding #137): the whole spec and
    the schema-unbounded ``_meta`` block. jsonschema bounds strings and
    array lengths; only byte budgets catch a spec bloated across many
    individually-legal fields (the permalink store keeps what validates,
    forever)."""
    violations: list[SpecViolation] = []
    if not isinstance(spec, Mapping):
        return violations

    def _byte_size(value: Any) -> int | None:
        try:
            return len(json.dumps(value, ensure_ascii=False).encode("utf-8"))
        except (TypeError, ValueError):
            return None  # unserialisable content refuses structurally

    total = _byte_size(spec)
    if total is not None and total > SPEC_MAX_BYTES:
        violations.append(
            SpecViolation(
                "<spec>",
                f"serialised spec is {total} bytes; the ceiling is "
                f"{SPEC_MAX_BYTES} bytes — ADR-020 expects ~1 KB specs, and the "
                "permalink store and renderer must stay bounded (review finding "
                "#137)",
            )
        )
    if "_meta" in spec:
        meta_size = _byte_size(spec["_meta"])
        if meta_size is not None and meta_size > META_MAX_BYTES:
            violations.append(
                SpecViolation(
                    "_meta",
                    f"_meta serialises to {meta_size} bytes; the ceiling is "
                    f"{META_MAX_BYTES} bytes — the provenance block is semantically "
                    "inert and must not become an unbounded payload (review "
                    "finding #137)",
                )
            )
    return violations


def _non_finite_violations(value: Any, path: str = "") -> list[SpecViolation]:
    """Every non-finite numeric leaf in the spec, as refusals naming the
    path. jsonschema cannot express finiteness portably, so this runs
    with the structural phase — before any semantic comparison can be
    silently disabled by NaN semantics (review finding #128)."""
    violations: list[SpecViolation] = []
    if isinstance(value, bool):
        return violations
    if isinstance(value, float) and not math.isfinite(value):
        violations.append(
            SpecViolation(
                path or "<root>",
                f"non-finite number {value!r} — every numeric field must be a "
                "finite RFC 8259 number; NaN/Infinity silently disable the "
                "domain-integrity comparisons (review finding #128)",
            )
        )
    elif isinstance(value, Mapping):
        for key, val in value.items():
            child = f"{path}.{key}" if path else str(key)
            violations.extend(_non_finite_violations(val, child))
    elif isinstance(value, Sequence) and not isinstance(value, str):
        for index, val in enumerate(value):
            violations.extend(_non_finite_violations(val, f"{path}[{index}]"))
    return violations


# ---------------------------------------------------------------------------
# Structural validation: JSON Schema errors -> SpecViolation
# ---------------------------------------------------------------------------


def _format_path(parts: Sequence[Any]) -> str:
    """Render a JSON-Schema absolute path (keys + array indices) as the
    dotted/bracketed spec-path syntax the refusal messages use."""
    out = ""
    for part in parts:
        if isinstance(part, int):
            out += f"[{part}]"
        elif out == "":
            out = str(part)
        else:
            out += f".{part}"
    return out


def _structural_violations(spec: Mapping[str, Any]) -> list[SpecViolation]:
    """Every JSON-Schema violation, each mapped to an actionable
    (path, reason) rooted at the offending property."""
    validator = Draft202012Validator(chartspec_schema())
    violations: list[SpecViolation] = []
    for error in validator.iter_errors(spec):
        base = list(error.absolute_path)
        if error.validator == "additionalProperties":
            allowed = set((error.schema or {}).get("properties", {}))
            instance = error.instance if isinstance(error.instance, Mapping) else {}
            for key in sorted(set(instance) - allowed):
                violations.append(
                    SpecViolation(
                        _format_path([*base, key]),
                        f"unknown property {key!r} is not in the frozen ChartSpec "
                        "vocabulary (additionalProperties: false — the LLM cannot "
                        "smuggle fields past the closed schema)",
                    )
                )
        elif error.validator == "required":
            required = error.validator_value or []
            instance = error.instance if isinstance(error.instance, Mapping) else {}
            for name in required:
                if name not in instance:
                    violations.append(
                        SpecViolation(
                            _format_path([*base, name]),
                            f"required field {name!r} is missing — the frozen "
                            "ChartSpec vocabulary requires it here",
                        )
                    )
        elif error.validator == "enum":
            allowed = ", ".join(repr(v) for v in error.validator_value)
            violations.append(
                SpecViolation(
                    _format_path(base),
                    f"value {error.instance!r} is not one of the allowed values "
                    f"({allowed}) — this field is a closed vocabulary",
                )
            )
        elif error.validator == "const":
            violations.append(
                SpecViolation(
                    _format_path(base),
                    f"value {error.instance!r} must be exactly "
                    f"{error.validator_value!r} in the frozen ChartSpec vocabulary",
                )
            )
        else:
            violations.append(
                SpecViolation(
                    _format_path(base) or "<root>",
                    f"schema violation ({error.validator}): {error.message}",
                )
            )
    return violations


# ---------------------------------------------------------------------------
# Semantic validation: cross-check the spec against the dataset manifest
# ---------------------------------------------------------------------------


def _coverage_ce(entry: Mapping[str, Any]) -> tuple[float, float] | None:
    """A dataset's parsed usable extent expressed in CE years (review #52).

    BP coverages convert via ``year_ce = present_ce - age_bp``. Returns
    None when the coverage/time-axis block is not shaped as expected (a
    guard — the manifest validator owns shape enforcement)."""
    coverage = entry.get("coverage") or {}
    time_axis = entry.get("time_axis") or {}
    unit = time_axis.get("unit")
    try:
        if unit == "year_ce":
            return float(coverage["first_year_ce"]), float(coverage["last_year_ce"])
        if unit == "years_bp":
            present = float(time_axis["present_ce"])
            return present - float(coverage["oldest_bp"]), present - float(coverage["youngest_bp"])
    except (KeyError, TypeError, ValueError):
        return None
    return None


def _year_text(year: Any) -> str | None:
    """A year as artefact text: ``1950``/``1950.0`` -> ``"1950"``."""
    if isinstance(year, bool) or not isinstance(year, (int, float)):
        return None
    if isinstance(year, float):
        return str(int(year)) if year.is_integer() else str(year)
    return str(year)


def _series_datasets(series: Mapping[str, Any]) -> list[str]:
    """The dataset ids a series plots (its ``dataset`` or its splice pair)."""
    if "dataset" in series:
        return [series["dataset"]]
    splice = series.get("splice_series")
    return list(splice) if isinstance(splice, Sequence) and not isinstance(splice, str) else []


def _series_coverage_ce(
    series: Mapping[str, Any], datasets: Mapping[str, Any]
) -> tuple[float, float] | None:
    """CE coverage extent for a series: a dataset's, or the *union* of a
    splice pair's members (review #52)."""
    extents = []
    for ds_id in _series_datasets(series):
        entry = datasets.get(ds_id)
        if not entry:
            return None
        extent = _coverage_ce(entry)
        if extent is None:
            return None
        extents.append(extent)
    if not extents:
        return None
    return min(e[0] for e in extents), max(e[1] for e in extents)


def _series_has_bp(series: Mapping[str, Any], datasets: Mapping[str, Any]) -> bool:
    for ds_id in _series_datasets(series):
        entry = datasets.get(ds_id)
        if entry and (entry.get("time_axis") or {}).get("unit") == "years_bp":
            return True
    return False


def _expected_units(
    series: Mapping[str, Any], datasets: Mapping[str, Any]
) -> tuple[set[str], str | None]:
    """The units a series' declared ``unit`` may legally take.

    Returns ``(units, converted_to)``: when a ``unit_conversion`` transform
    is present the only legal unit is its ``to_unit``; otherwise it is the
    source dataset(s)' ``variable.unit``."""
    converted_to: str | None = None
    for transform in series.get("transforms") or []:
        if isinstance(transform, Mapping) and transform.get("op") == "unit_conversion":
            converted_to = transform.get("to_unit")
    if converted_to is not None:
        return {converted_to}, converted_to
    units: set[str] = set()
    for ds_id in _series_datasets(series):
        entry = datasets.get(ds_id)
        if entry:
            unit = (entry.get("variable") or {}).get("unit")
            if unit is not None:
                units.add(unit)
    return units, None


def validate_spec(
    spec: Mapping[str, Any],
    manifest: Mapping[str, Any],
    data_extents: Mapping[str, tuple[float, float]] | None = None,
) -> None:
    """Validate one ChartSpec against the schema and the dataset manifest.

    Returns ``None`` for a valid spec; raises :class:`ChartSpecError`
    carrying **every** violation found otherwise. Pure code — the ADR-020
    guarantee that chart legality is decided by code, never the model.

    ``manifest`` is the raw ``datasets/manifest.yaml`` mapping (``datasets``
    keyed by id with ``time_axis``/``variable``/``coverage``;
    ``splice_pairs`` with ``overlap`` and ``rebaseline`` blocks).

    ``data_extents`` maps series id → ``(min, max)`` of that series' plotted
    values (post-transform, within the spec's time range), computed by the
    caller from the loaded frames. When ``None`` (planner-time structural
    validation, before any data is loaded) the extent-containment check is
    skipped. The render path (#17) does not call this function directly:
    it consumes :func:`validate_spec_for_render`, whose
    :class:`RenderValidatedSpec` return type structurally proves the
    extents-aware checks ran (review finding #133).

    Checks, beyond schema shape (each refusal names its spec path):

    - every referenced dataset id exists in ``manifest.datasets`` and is in
      the chart pack (``in_chart_pack``; review finding #117 — provisional
      datasets refuse by name, naming the pending confirmation issue #23);
    - ``series[*].unit`` equals the dataset's ``variable.unit`` (or the
      ``to_unit`` of a ``unit_conversion`` transform on that series);
    - ``splice_pair_id`` names a manifest ``splice_pairs`` entry whose
      members are both in the chart pack; ``splice_series`` equals exactly
      ``[pair.paleo, pair.instrumental]``; the mandatory
      ``annotations.splice_point`` / ``resolution_note`` are present and the
      splice year equals the pair's ``splice_year_ce``;
    - ``overlap_policy`` is present on every spliced series and equals the
      pair's manifest ``overlap.policy`` (review finding #47);
    - ``rebaseline_to`` presence matches the pair's manifest ``rebaseline``;
      ``apply_to`` and ``alignment_period_ce`` equal the manifest values;
      ``alignment_disclosure`` equals the manifest ``rebaseline.disclosure``
      verbatim (review finding #50);
    - time ranges lie within each series' dataset coverage — for a splice,
      within the union of the members' coverage (review finding #52). A
      series over a ``years_bp`` dataset in a CE-ranged spec without
      ``time_axis.convert_bp: true`` is a coverage-unit mismatch, refused at
      ``time_axis``;
    - ``scale_domain``: required per series for ``context_recent_inset``;
      when ``data_extents`` is given, each domain must contain its series'
      extent (review finding #48); any domain that excludes zero requires
      the series' ``annotations.non_zero_baseline`` label;
    - ``uncertainty_band.source`` names one of the series' datasets;
    - panel-pair rules: ``panels`` present iff ``chart_type`` is
      ``context_recent_inset``; the recent range within the context range;
      ``shared_y_scale_with`` names an existing panel.

    Phase discipline (review finding #126): the semantic cross-checks
    assume a structurally valid spec, so any structural violation —
    including a non-object top-level spec — raises immediately with the
    structural refusals alone. The semantic phase never sees a mistyped
    subtree, so no raw ``TypeError``/``AttributeError`` can escape this
    function: every refusal is a :class:`ChartSpecError`.
    """
    structural = list(_structural_violations(spec))
    structural.extend(_non_finite_violations(spec))
    structural.extend(_size_violations(spec))
    if structural or not isinstance(spec, Mapping):
        _raise_violations(
            structural
            or [
                SpecViolation(
                    "<root>",
                    f"a ChartSpec must be a JSON object, not {type(spec).__name__}",
                )
            ]
        )
    violations: list[SpecViolation] = []

    datasets = manifest.get("datasets") or {}
    pairs = {p.get("id"): p for p in (manifest.get("splice_pairs") or []) if isinstance(p, Mapping)}
    chart_type = spec.get("chart_type")
    time_axis = spec.get("time_axis") or {}
    convert_bp = time_axis.get("convert_bp") is True
    series_list = spec.get("series") if isinstance(spec.get("series"), list) else []

    time_axis_flagged = False

    def add(path: str, reason: str) -> None:
        violations.append(SpecViolation(path, reason))

    def flag_time_axis(reason: str) -> None:
        nonlocal time_axis_flagged
        if not time_axis_flagged:
            add("time_axis", reason)
            time_axis_flagged = True

    def check_year_pair(path: str, pair: Any) -> bool:
        """Strictly-increasing rule for every [start, end] pair (review
        finding #130). Returns True when the pair is well-ordered, so
        callers can gate follow-on checks that assume it."""
        if not (isinstance(pair, Sequence) and not isinstance(pair, str) and len(pair) == 2):
            return False
        start, end = pair[0], pair[1]
        if not start < end:
            add(
                path,
                f"[start, end] pair {list(pair)!r} must be strictly increasing "
                "(start < end) — an inverted or zero-width range renders a blank "
                "frame or a mirror-imaged axis (review finding #130)",
            )
            return False
        return True

    for index, series in enumerate(series_list):
        if not isinstance(series, Mapping):
            continue
        prefix = f"series[{index}]"
        has_dataset = "dataset" in series
        has_splice = "splice_series" in series or "splice_pair_id" in series

        # Exactly one data source (dataset XOR splice pair).
        if has_dataset and has_splice:
            add(
                f"{prefix}.dataset",
                "a series carries exactly one data source: either a single "
                "'dataset' or a 'splice_series'/'splice_pair_id' pair, never both",
            )
        elif not has_dataset and not has_splice:
            add(
                f"{prefix}.dataset",
                "a series must name a data source: a single 'dataset' or a "
                "'splice_series'/'splice_pair_id' pair",
            )

        dataset_ok = False
        # --- plain-dataset series ------------------------------------
        if has_dataset and not has_splice:
            try:
                pack.require_in_chart_pack(manifest, series["dataset"])
                dataset_ok = True
            except ValueError as exc:
                add(f"{prefix}.dataset", str(exc))

        pair = None
        # --- splice-only fields on unspliced series (review #127) ----
        # Rebaselining, overlap policy and the splice annotations exist
        # only as manifest splice-pair decisions (ADR-020, amendments
        # 1-2, review #47). On a series without a splice pair they are
        # either an LLM-chosen alignment (the cherry-pick the curation
        # rule refuses) or a false disclosure baked into the artefact.
        if not has_splice:
            if "rebaseline_to" in series:
                add(
                    f"{prefix}.rebaseline_to",
                    "rebaseline_to is only legal on a spliced series whose manifest "
                    "splice pair records the alignment — rebaselining is a "
                    "curation-time decision fixed in the dataset manifest, never an "
                    "LLM choice on a plain series (ADR-020, review finding #127)",
                )
            if "overlap_policy" in series:
                add(
                    f"{prefix}.overlap_policy",
                    "overlap_policy discloses what happened to overlapping splice "
                    "samples; on a series without a splice pair it would render a "
                    "disclosure for data that was never discarded (review finding "
                    "#127)",
                )
            annotations = series.get("annotations") or {}
            if "splice_point" in annotations:
                add(
                    f"{prefix}.annotations.splice_point",
                    "a splice_point annotation on a series without a splice pair "
                    "marks a splice that does not exist — a fake splice marker on "
                    "continuous data is the mirror image of the hidden-splice "
                    "attack DESIGN §3.7 annotates against (review finding #127)",
                )
            if "resolution_note" in annotations:
                add(
                    f"{prefix}.annotations.resolution_note",
                    "a resolution_note describes the resolution change across a "
                    "splice; on a series without a splice pair it asserts a "
                    "resolution change that does not exist (review finding #127)",
                )

        # --- spliced series ------------------------------------------
        if has_splice:
            pair_id = series.get("splice_pair_id")
            if pair_id not in pairs:
                add(
                    f"{prefix}.splice_pair_id",
                    f"splice_pair_id {pair_id!r} does not name any splice_pairs "
                    "entry in the dataset manifest (splicing is manifest-keyed, "
                    "ADR-020)",
                )
            else:
                pair = pairs[pair_id]
                try:
                    pack.require_renderable_splice_pair(manifest, pair_id)
                    dataset_ok = True
                except ValueError as exc:
                    add(f"{prefix}.splice_pair_id", str(exc))

                expected_members = [pair.get("paleo"), pair.get("instrumental")]
                if list(series.get("splice_series") or []) != expected_members:
                    add(
                        f"{prefix}.splice_series",
                        f"splice_series {series.get('splice_series')!r} must equal the "
                        f"manifest pair {pair_id!r} members "
                        f"[paleo, instrumental] = {expected_members!r}",
                    )

            annotations = series.get("annotations") or {}
            if "splice_point" not in annotations:
                add(
                    f"{prefix}.annotations.splice_point",
                    "a spliced series must carry annotations.splice_point (the "
                    "rendered splice marker) — an unannotated splice is the "
                    "hidden-smoothing attack surface (DESIGN §3.7)",
                )
            elif pair is not None:
                splice_point = annotations.get("splice_point") or {}
                year = splice_point.get("year_ce")
                manifest_year = pair.get("splice_year_ce")
                if year != manifest_year:
                    add(
                        f"{prefix}.annotations.splice_point.year_ce",
                        f"splice_point.year_ce {year!r} must equal the manifest "
                        f"pair {series.get('splice_pair_id')!r} splice_year_ce "
                        f"{manifest_year!r} (fixed at curation time, ADR-020)",
                    )
                # The rendered marker label must name the splice year
                # (review #131 minimum rule — full manifest ownership of
                # the label is deferred until the pairs carry a
                # splice_label field): a marker whose label hides the
                # year defeats the marker's purpose.
                year_text = _year_text(manifest_year)
                label = splice_point.get("label")
                if year_text and isinstance(label, str) and year_text not in label:
                    add(
                        f"{prefix}.annotations.splice_point.label",
                        f"splice_point.label {label!r} must name the manifest splice "
                        f"year {year_text} — the rendered marker exists to disclose "
                        "when the splice happens (review finding #131)",
                    )
            if "resolution_note" not in annotations:
                add(
                    f"{prefix}.annotations.resolution_note",
                    "a spliced series must carry annotations.resolution_note "
                    "describing the resolution change across the splice (DESIGN §3.7)",
                )
            elif pair is not None and annotations["resolution_note"] != pair.get("resolution_note"):
                add(
                    f"{prefix}.annotations.resolution_note",
                    f"resolution_note {annotations['resolution_note']!r} must equal "
                    f"the manifest pair {series.get('splice_pair_id')!r} "
                    f"resolution_note {pair.get('resolution_note')!r} verbatim — the "
                    "manifest owns the resolution disclosure so an LLM-authored note "
                    "cannot deny the smoothing it exists to disclose (vocabulary "
                    "amendment 1, review finding #131; same rule as the #50 "
                    "alignment disclosure)",
                )

            # overlap policy (review #47)
            if "overlap_policy" not in series:
                add(
                    f"{prefix}.overlap_policy",
                    "a spliced series must declare overlap_policy: silence about "
                    "what happens to overlapping source samples is the residual "
                    "'hidden the decline' attack (review finding #47)",
                )
            elif pair is not None and series["overlap_policy"] in OVERLAP_POLICIES:
                manifest_policy = (pair.get("overlap") or {}).get("policy")
                if manifest_policy is not None and series["overlap_policy"] != manifest_policy:
                    add(
                        f"{prefix}.overlap_policy",
                        f"overlap_policy {series['overlap_policy']!r} must equal the "
                        f"manifest pair {series.get('splice_pair_id')!r} overlap.policy "
                        f"{manifest_policy!r} — the LLM cannot re-decide a curation call",
                    )

            # rebaseline (ADR-020 / review #50)
            if pair is not None:
                manifest_rebaseline = pair.get("rebaseline")
                has_rebaseline_to = "rebaseline_to" in series
                if manifest_rebaseline and not has_rebaseline_to:
                    add(
                        f"{prefix}.rebaseline_to",
                        f"the manifest pair {series.get('splice_pair_id')!r} defines a "
                        "rebaseline, so this series must carry a matching rebaseline_to",
                    )
                elif not manifest_rebaseline and has_rebaseline_to:
                    add(
                        f"{prefix}.rebaseline_to",
                        f"the manifest pair {series.get('splice_pair_id')!r} records no "
                        "rebaseline (rebaseline: null), so this series must not carry "
                        "rebaseline_to",
                    )
                elif manifest_rebaseline and has_rebaseline_to:
                    rb = series["rebaseline_to"] or {}
                    if rb.get("apply_to") != manifest_rebaseline.get("apply_to"):
                        add(
                            f"{prefix}.rebaseline_to.apply_to",
                            f"rebaseline_to.apply_to {rb.get('apply_to')!r} must equal "
                            f"the manifest-fixed member {manifest_rebaseline.get('apply_to')!r}"
                            " — shifting the wrong series moves a reconstruction off its "
                            "native reference",
                        )
                    elif rb.get("apply_to") not in _series_datasets(series):
                        # Defence in depth (review #127): even a manifest
                        # rebaseline entry cannot authorise shifting a
                        # dataset that is not a member of this series'
                        # splice pair.
                        add(
                            f"{prefix}.rebaseline_to.apply_to",
                            f"rebaseline_to.apply_to {rb.get('apply_to')!r} must name a "
                            f"member of this series' splice pair "
                            f"{_series_datasets(series)!r} — a rebaseline can only "
                            "shift a plotted splice member (review finding #127)",
                        )
                    if list(rb.get("alignment_period_ce") or []) != list(
                        manifest_rebaseline.get("alignment_period_ce") or []
                    ):
                        add(
                            f"{prefix}.rebaseline_to.alignment_period_ce",
                            f"alignment_period_ce {rb.get('alignment_period_ce')!r} must "
                            f"equal the manifest-fixed period "
                            f"{list(manifest_rebaseline.get('alignment_period_ce') or [])!r} "
                            "— the alignment period is a curation-time decision, never the "
                            "LLM's (ADR-020)",
                        )
                    disclosure = rb.get("alignment_disclosure")
                    manifest_disclosure = manifest_rebaseline.get("disclosure")
                    if (
                        disclosure is not None
                        and manifest_disclosure is not None
                        and disclosure != manifest_disclosure
                    ):
                        add(
                            f"{prefix}.rebaseline_to.alignment_disclosure",
                            "alignment_disclosure must equal the manifest "
                            "rebaseline.disclosure verbatim so the alignment method on "
                            "the artefact cannot drift from the curation record "
                            "(review finding #50)",
                        )

        # --- unit label matches source (or its conversion) -----------
        if dataset_ok and "unit" in series:
            allowed_units, converted_to = _expected_units(series, datasets)
            if allowed_units and series["unit"] not in allowed_units:
                if converted_to is not None:
                    reason = (
                        f"series unit {series['unit']!r} must equal the "
                        f"unit_conversion to_unit {converted_to!r} — a mismatch is a "
                        "mislabelled axis"
                    )
                else:
                    expected = ", ".join(repr(u) for u in sorted(allowed_units))
                    reason = (
                        f"series unit {series['unit']!r} must equal the dataset "
                        f"variable unit ({expected}) — a mismatch is a mislabelled axis"
                    )
                add(f"{prefix}.unit", reason)

        # --- per-op transform parameters (review #132) ---------------
        source_units: set[str] = set()
        for ds_id in _series_datasets(series):
            entry = datasets.get(ds_id)
            if entry:
                unit = (entry.get("variable") or {}).get("unit")
                if unit is not None:
                    source_units.add(unit)
        conversions_seen = 0
        for t_index, transform in enumerate(series.get("transforms") or []):
            op = transform.get("op")
            allowed_params = TRANSFORM_PARAMS.get(op)
            if allowed_params is None:
                continue  # unknown op already refused structurally
            t_prefix = f"{prefix}.transforms[{t_index}]"
            for param in sorted(set(transform) - {"op"} - allowed_params):
                add(
                    f"{t_prefix}.{param}",
                    f"parameter {param!r} is not legal on op {op!r} — each transform "
                    f"op carries exactly its own parameters "
                    f"({sorted(allowed_params) or 'none'}), no cross-op smuggling "
                    "(review finding #132)",
                )
            for param in sorted(allowed_params - set(transform)):
                add(
                    f"{t_prefix}.{param}",
                    f"op {op!r} requires parameter {param!r} — omitting it hands #17 "
                    "a contradictory or renderer-implicit instruction (review "
                    "finding #132)",
                )
            if "window_years" in allowed_params:
                window = transform.get("window_years")
                if isinstance(window, (int, float)) and not isinstance(window, bool):
                    if not 0 < window <= MAX_WINDOW_YEARS:
                        add(
                            f"{t_prefix}.window_years",
                            f"window_years {window!r} must be positive and at most "
                            f"{MAX_WINDOW_YEARS!r} — the coarsest pack resolution is "
                            "a 100-year bin, so a longer window smooths harder than "
                            "the data legitimises (review finding #132)",
                        )
            if op == "unit_conversion":
                conversions_seen += 1
                if conversions_seen > 1:
                    add(
                        f"{t_prefix}.op",
                        "at most one unit_conversion per series — chained "
                        "conversions have no code-owned table entry (review "
                        "finding #132)",
                    )
                to_unit = transform.get("to_unit")
                if isinstance(to_unit, str) and dataset_ok and source_units:
                    for source_unit in sorted(source_units):
                        if (source_unit, to_unit) not in UNIT_CONVERSIONS:
                            add(
                                f"{t_prefix}.to_unit",
                                f"no code-owned conversion from {source_unit!r} to "
                                f"{to_unit!r} exists in UNIT_CONVERSIONS — the axis "
                                "unit is pinned to the manifest unit or a table "
                                "conversion, never free text (review finding #132)",
                            )

        # --- baseline reference line (review #134) -------------------
        # Decision (recorded): the only legal baseline.value is 0 — the
        # reference-period zero line, the sole committed use. Any other
        # reference line is a model-supplied number drawn as a labelled
        # rule on the artefact (against the ADR-020 extension) and waits
        # for a manifest-anchored vocabulary entry.
        if "baseline" in series and isinstance(series["baseline"], Mapping):
            baseline = series["baseline"]
            if baseline.get("value") != 0:
                add(
                    f"{prefix}.baseline.value",
                    f"baseline.value {baseline.get('value')!r} must be 0 (the "
                    "reference-period zero line) — any other reference line is a "
                    "model-supplied number on the artefact; manifest-anchored "
                    "reference values are a future vocabulary entry (review "
                    "finding #134)",
                )
            # On a rebaselined series the label's reference period must
            # match the manifest display_reference (mirror of #50).
            display_reference = ((pair or {}).get("rebaseline") or {}).get("display_reference")
            label = baseline.get("label")
            if "rebaseline_to" in series and isinstance(display_reference, str):
                reference_years = re.findall(r"\d{3,4}", display_reference)
                missing_years = [
                    year
                    for year in reference_years
                    if not isinstance(label, str) or year not in label
                ]
                if missing_years:
                    add(
                        f"{prefix}.baseline.label",
                        f"baseline.label {label!r} must name the manifest display "
                        f"reference period ({display_reference!r}; years "
                        f"{', '.join(reference_years)}) — a zero-line label claiming "
                        "a different reference period is numerically false on the "
                        "artefact (review finding #134)",
                    )

        # --- uncertainty band source is a series member --------------
        if "uncertainty_band" in series:
            source = (series["uncertainty_band"] or {}).get("source")
            members = _series_datasets(series)
            if source not in members:
                add(
                    f"{prefix}.uncertainty_band.source",
                    f"uncertainty_band.source {source!r} must be one of this series' "
                    f"datasets {members!r} — a band attaches to a splice member "
                    "(amendment 6)",
                )

        # --- scale-domain integrity (review #48) ---------------------
        if chart_type == "context_recent_inset" and "scale_domain" not in series:
            add(
                f"{prefix}.scale_domain",
                "context_recent_inset requires an explicit scale_domain on every "
                "series — shared per-axis domains across panels cannot be implicit "
                "(amendment 5)",
            )
        domain = series.get("scale_domain")
        annotations = series.get("annotations") or {}
        excludes_zero = False
        if (
            isinstance(domain, Sequence)
            and not isinstance(domain, str)
            and len(domain) == 2
            and check_year_pair(f"{prefix}.scale_domain", domain)
        ):
            low, high = domain[0], domain[1]
            excludes_zero = low > 0 or high < 0
            if excludes_zero and "non_zero_baseline" not in annotations:
                add(
                    f"{prefix}.annotations.non_zero_baseline",
                    f"scale_domain {list(domain)!r} excludes zero, so the series must "
                    "carry annotations.non_zero_baseline naming the truncated axis "
                    "(review finding #48; §3.7 per-axis rule)",
                )
            if data_extents is not None and series.get("id") in data_extents:
                emin, emax = data_extents[series["id"]]
                if emin < low or emax > high:
                    add(
                        f"{prefix}.scale_domain",
                        f"scale_domain {list(domain)!r} does not contain the plotted "
                        f"extent ({emin}, {emax}) — clipping or flattening the data by "
                        "the axis window is cherry-picking (review finding #48)",
                    )
                # Zoom-out bound (review #129): containment alone admits
                # the inverse cherry-pick — a domain so wide the signal
                # renders as a flat line. Bound the span relative to the
                # data span, with a free allowance for extending the
                # zero-side edge to zero (see SCALE_DOMAIN_MAX_SPAN_FACTOR).
                data_span = emax - emin
                if data_span > 0:
                    zero_allowance = max(emin, 0.0) if emin > 0 else max(-emax, 0.0)
                    max_span = SCALE_DOMAIN_MAX_SPAN_FACTOR * data_span + zero_allowance
                    if (high - low) > max_span:
                        add(
                            f"{prefix}.scale_domain",
                            f"scale_domain {list(domain)!r} spans {high - low!r} but the "
                            f"plotted extent ({emin}, {emax}) spans only {data_span!r} — "
                            "an over-wide axis flattens the signal into a flat line, the "
                            "inverse cherry-pick of clipping (review finding #129; max "
                            f"span is {SCALE_DOMAIN_MAX_SPAN_FACTOR}x the data span plus "
                            "the extension to zero)",
                        )
        if "non_zero_baseline" in annotations and not excludes_zero:
            add(
                f"{prefix}.annotations.non_zero_baseline",
                "annotations.non_zero_baseline asserts a zero-excluding axis, but "
                "this series' scale_domain does not exclude zero (or is absent) — "
                "a false truncation disclosure (review finding #127); the validator "
                "owns this rule, not the renderer",
            )

        # --- coverage-unit gate (review #52 / amendment 8) -----------
        if _series_has_bp(series, datasets) and not convert_bp:
            flag_time_axis(
                "a series over a years_bp dataset needs time_axis.convert_bp: true; "
                "without it the spec's CE ranges cannot be compared against BP coverage "
                "at all (amendment 8)",
            )

    # --- time-range coverage containment (review #52) ----------------
    def _check_range_within_coverage(range_path: str, time_range: Any) -> None:
        if not (
            isinstance(time_range, Sequence)
            and not isinstance(time_range, str)
            and len(time_range) == 2
        ):
            return
        start, end = time_range[0], time_range[1]
        for series in series_list:
            if not isinstance(series, Mapping):
                continue
            if _series_has_bp(series, datasets) and not convert_bp:
                continue
            extent = _series_coverage_ce(series, datasets)
            if extent is None:
                continue
            cov_min, cov_max = extent
            for ds_id in _series_datasets(series):
                if start < cov_min:
                    add(
                        range_path,
                        f"{range_path} start {start!r} is before dataset {ds_id!r} "
                        f"coverage start {cov_min!r} (coverage is the parsed usable "
                        "extent, review finding #52)",
                    )
                    break
                if end > cov_max:
                    add(
                        range_path,
                        f"{range_path} end {end!r} is after dataset {ds_id!r} coverage "
                        f"end {cov_max!r} (coverage is the parsed usable extent, "
                        "review finding #52)",
                    )
                    break

    # --- panel-pair rules (amendments 4-5) + range containment -------
    panels = spec.get("panels")
    if chart_type == "context_recent_inset":
        # The panels own the time ranges (amendment 4): a top-level
        # time_range_ce would be an unvalidated field in a validated
        # document — dead weight with a permalink-hash consequence and
        # an undefined renderer meaning (review finding #135).
        if "time_range_ce" in spec:
            add(
                "time_range_ce",
                "time_range_ce is not valid on a context_recent_inset spec — the "
                "panels own the time ranges (amendment 4), so a top-level range "
                "would be ignored yet still change the permalink hash (review "
                "finding #135)",
            )
        if panels is None:
            add(
                "panels",
                "context_recent_inset requires a panels block with a context and a "
                "recent panel (amendment 4)",
            )
        elif isinstance(panels, Mapping):
            context = panels.get("context") if isinstance(panels.get("context"), Mapping) else {}
            recent = panels.get("recent") if isinstance(panels.get("recent"), Mapping) else {}
            recent_range = recent.get("time_range_ce")
            context_range = context.get("time_range_ce")
            context_ok = "time_range_ce" not in context or check_year_pair(
                "panels.context.time_range_ce", context_range
            )
            recent_ok = "time_range_ce" not in recent or check_year_pair(
                "panels.recent.time_range_ce", recent_range
            )
            if (
                context_ok
                and recent_ok
                and isinstance(recent_range, Sequence)
                and not isinstance(recent_range, str)
                and len(recent_range) == 2
                and isinstance(context_range, Sequence)
                and not isinstance(context_range, str)
                and len(context_range) == 2
            ):
                if recent_range[0] < context_range[0] or recent_range[1] > context_range[1]:
                    add(
                        "panels.recent.time_range_ce",
                        f"the recent panel range {list(recent_range)!r} must lie within "
                        f"the context panel range {list(context_range)!r} (the inset is "
                        "a zoom of the context, amendment 4)",
                    )
                # Strict-zoom + minimum-span rules (review #130): an inset
                # spanning the whole context is a decorative duplicate; a
                # sliver below the minimum span is information-free.
                recent_width = recent_range[1] - recent_range[0]
                context_width = context_range[1] - context_range[0]
                if recent_width >= context_width:
                    add(
                        "panels.recent.time_range_ce",
                        f"the recent panel range {list(recent_range)!r} spans the whole "
                        f"context range {list(context_range)!r} — the inset must be a "
                        "strict zoom (narrower than the context), or the panel pair is "
                        "a decorative duplicate (review finding #130)",
                    )
                elif recent_width < MIN_RECENT_PANEL_SPAN_YEARS:
                    add(
                        "panels.recent.time_range_ce",
                        f"the recent panel range {list(recent_range)!r} spans "
                        f"{recent_width!r} years — the inset needs at least "
                        f"{MIN_RECENT_PANEL_SPAN_YEARS!r} years to show any trend at "
                        "annual resolution (review finding #130)",
                    )
            for panel_name in ("context", "recent"):
                panel = panels.get(panel_name)
                if not isinstance(panel, Mapping):
                    continue
                if "shared_y_scale_with" in panel and panel["shared_y_scale_with"] not in (
                    "context",
                    "recent",
                ):
                    add(
                        f"panels.{panel_name}.shared_y_scale_with",
                        f"shared_y_scale_with {panel['shared_y_scale_with']!r} must name "
                        "an existing panel (context or recent)",
                    )
                _check_range_within_coverage(
                    f"panels.{panel_name}.time_range_ce", panel.get("time_range_ce")
                )
    else:
        if panels is not None:
            add(
                "panels",
                f"panels is only valid for chart_type 'context_recent_inset', not "
                f"{chart_type!r} — the panel pair is that type's layout wrapper "
                "(amendment 4)",
            )
        if "time_range_ce" in spec and check_year_pair("time_range_ce", spec.get("time_range_ce")):
            _check_range_within_coverage("time_range_ce", spec.get("time_range_ce"))

    if violations:
        _raise_violations(violations)
    return None


def _raise_violations(violations: list[SpecViolation]) -> None:
    """Raise :class:`ChartSpecError`, de-duplicating identical
    (path, reason) pairs (a BP series flagged for both panels would
    otherwise repeat) while preserving order."""
    seen: set[tuple[str, str]] = set()
    unique: list[SpecViolation] = []
    for violation in violations:
        key = (violation.path, violation.reason)
        if key not in seen:
            seen.add(key)
            unique.append(violation)
    raise ChartSpecError(unique)


# ---------------------------------------------------------------------------
# Render-mode validation: the structural extents contract (review #133)
# ---------------------------------------------------------------------------

_RENDER_TOKEN = object()


@dataclass(frozen=True)
class RenderValidatedSpec:
    """Proof that a spec passed **render-mode** validation (review #133).

    The renderer's artefact entry point (#17) must require this type —
    not a bare mapping — so the extents-aware chart-integrity checks
    (scale-domain containment and flattening, reviews #48/#129) are
    structurally guaranteed to have run before any pixel is produced.
    Constructible only via :func:`validate_spec_for_render`; direct
    construction raises ``TypeError``. This is the same
    advisory-prose-to-structure move review #117 made for pack gating.
    """

    spec: Mapping[str, Any]
    data_extents: Mapping[str, tuple[float, float]]
    _token: Any = field(default=None, repr=False, compare=False)

    def __post_init__(self) -> None:
        if self._token is not _RENDER_TOKEN:
            raise TypeError(
                "RenderValidatedSpec is constructible only via "
                "validate_spec_for_render (review finding #133): the render path "
                "must prove the extents-aware validation ran"
            )


def validate_spec_for_render(
    spec: Mapping[str, Any],
    manifest: Mapping[str, Any],
    data_extents: Mapping[str, tuple[float, float]] | None,
) -> RenderValidatedSpec:
    """Render-mode validation: :func:`validate_spec` with extents
    **mandatory and complete** (review finding #133).

    Refuses ``data_extents=None`` and any spec series whose id is missing
    from the mapping (a partial-extents dict would otherwise silently
    skip the #48/#129 scale-domain checks for that series). On success
    returns the :class:`RenderValidatedSpec` token the renderer (#17)
    requires. ``validate_spec`` remains the planner-time surface, where
    extents are legitimately not yet computable.
    """
    violations: list[SpecViolation] = []
    if data_extents is None:
        violations.append(
            SpecViolation(
                "series",
                "extent unavailable — render-time validation requires computed "
                "extents for every plotted series; extents=None is only legal at "
                "planner time, through validate_spec (review finding #133)",
            )
        )
    elif isinstance(spec, Mapping):
        series_list = spec.get("series") if isinstance(spec.get("series"), list) else []
        for index, series in enumerate(series_list):
            if isinstance(series, Mapping) and series.get("id") not in data_extents:
                violations.append(
                    SpecViolation(
                        f"series[{index}].scale_domain",
                        f"extent unavailable for series id {series.get('id')!r} — "
                        "render-time validation requires computed extents for every "
                        "plotted series; a partial extents mapping would silently "
                        "skip the scale-domain integrity checks (review finding "
                        "#133)",
                    )
                )
    try:
        validate_spec(spec, manifest, data_extents=data_extents)
    except ChartSpecError as err:
        violations.extend(err.violations)
    if violations:
        _raise_violations(violations)
    return RenderValidatedSpec(spec, data_extents, _RENDER_TOKEN)


# ---------------------------------------------------------------------------
# Canonical spec hashing (for /chart/<hash> permalinks)
# ---------------------------------------------------------------------------


def _canonicalize(value: Any) -> Any:
    """Recursively canonicalise for hashing: integer-valued floats collapse
    to ints (``1959.0`` == ``1959``); dicts/lists rebuilt structurally.

    ``bool`` is preserved (it is an ``int`` subclass but not a number here)."""
    if isinstance(value, bool):
        return value
    if isinstance(value, float):
        return int(value) if value.is_integer() else value
    if isinstance(value, Mapping):
        return {key: _canonicalize(val) for key, val in value.items()}
    if isinstance(value, (list, tuple)):
        return [_canonicalize(item) for item in value]
    return value


def spec_hash(spec: Mapping[str, Any]) -> str:
    """Canonical content hash of a ChartSpec, for ``/chart/<hash>`` permalinks.

    Returns a 64-char lowercase hex sha256 over a canonical serialisation.
    Contract (pinned by tests):

    - key order never matters (deep canonicalisation, sorted keys);
    - the top-level ``_meta`` block is excluded (provenance/sign-off notes
      are not chart semantics);
    - numbers are canonicalised so ``1959`` and ``1959.0`` hash identically
      (migration-safe: a serialiser that floats an int must not move every
      permalink);
    - any semantic change — title, ranges, domains, spec_version, series —
      changes the hash.

    Pure and deterministic across processes and platforms.
    """
    payload = {key: value for key, value in spec.items() if key != "_meta"}
    canonical = _canonicalize(payload)
    try:
        serialised = json.dumps(
            canonical,
            sort_keys=True,
            separators=(",", ":"),
            ensure_ascii=False,
            allow_nan=False,
        )
    except ValueError as exc:
        # allow_nan=False: NaN/Infinity would serialise to non-RFC-8259
        # tokens no strict consumer can parse — a non-finite spec never
        # mints a permalink (review finding #128).
        raise ChartSpecError(
            [
                SpecViolation(
                    "<spec>",
                    "spec contains a non-finite number (NaN/Infinity) — the "
                    "canonical serialisation is RFC 8259 only, so no permalink "
                    "hash is minted (review finding #128)",
                )
            ]
        ) from exc
    return hashlib.sha256(serialised.encode("utf-8")).hexdigest()


# ---------------------------------------------------------------------------
# In-repo schema documentation for the planner prompt (#16)
# ---------------------------------------------------------------------------


def render_schema_doc() -> str:
    """The in-repo ChartSpec doc for the planner prompt (#16), as Markdown.

    Deterministically derived from :func:`chartspec_schema` so the doc
    cannot drift from the schema: the committed ``charts/CHARTSPEC.md``
    must equal this function's output byte-for-byte (pinned by
    ``test_schema_doc_matches_schema``), and the text names every chart
    type, transform op and overlap policy plus the load-bearing field
    names. Ends with a newline (end-of-file hook).
    """
    chart_types = ", ".join(f"`{name}`" for name in sorted(CHART_TYPES))
    transform_ops = ", ".join(f"`{name}`" for name in sorted(TRANSFORM_OPS))
    overlap_policies = ", ".join(f"`{name}`" for name in sorted(OVERLAP_POLICIES))

    lines = [
        "# ChartSpec vocabulary (issue #15)",
        "",
        "> Generated from `charts.spec.chartspec_schema()` by",
        "> `charts.spec.render_schema_doc()`. Do not edit by hand — the test",
        "> `test_schema_doc_matches_schema` pins this file byte-for-byte to the",
        "> schema, so it can never drift from what the validator enforces.",
        "",
        "The chart planner (#16) emits a **ChartSpec** — a JSON document, never",
        "code. `charts.spec.validate_spec` decides legality in pure code and",
        "cross-checks every curation-time decision against `datasets/manifest.yaml`",
        "(ADR-020): the model supplies neither numbers, pixels, nor artefact text.",
        "The schema is closed everywhere (`additionalProperties: false`); the only",
        "tolerated extra is a top-level `_meta` provenance block, which is ignored",
        "semantically and excluded from the permalink hash.",
        "",
        "## Closed vocabularies",
        "",
        f"- **chart_type** — one of: {chart_types}. The five MVP types are a closed",
        "  enum; warming stripes and other Phase 2 types are not expressible.",
        f"- **transforms[*].op** — one of: {transform_ops}. These generic transforms",
        "  live in a per-series `transforms` list. A `unit_conversion` carries only",
        "  `to_unit`; the conversion arithmetic is code-owned (no LLM-authored",
        "  factor).",
        f"- **overlap_policy** — one of: {overlap_policies}. What a spec may carry for",
        "  a given splice is further narrowed to the manifest-legal value recorded in",
        "  that pair's `overlap.policy` (review finding #47).",
        "",
        "## Top-level fields",
        "",
        "- **spec_version**, **chart_id**, **chart_type**, **title** — required.",
        "  **subtitle** is optional.",
        "- **time_range_ce** `[start, end]` — CE years for a single-panel chart; must",
        "  lie within every series' dataset coverage (the parsed usable extent,",
        "  review finding #52).",
        '- **time_axis** `{calendar: "CE", convert_bp: <bool>}` — set `convert_bp:',
        "  true` when any series plots a `years_bp` dataset on the CE axis. BCE-aware",
        "  axis labelling is renderer-owned time_axis semantics (amendment 8); there",
        "  is no per-spec label/tick styling field.",
        "- **panels** — present if and only if `chart_type` is `context_recent_inset`.",
        "  A `context` and a `recent` panel, each with a `label` and a",
        "  `time_range_ce`; the recent range must lie within the context range, and",
        "  `shared_y_scale_with` names the other panel (amendments 4-5).",
        "- **series** — one or more series (see below).",
        "",
        "## Series fields",
        "",
        "A series names exactly one data source: a single `dataset`, or a splice",
        "pair (`splice_series` + `splice_pair_id`). Both must resolve to chart-pack",
        "datasets (`in_chart_pack`, review finding #117).",
        "",
        "- **id**, **label**, **unit** — required. `unit` must equal the source",
        "  dataset's variable unit (or a `unit_conversion` transform's `to_unit`).",
        "- **axis** `left|right`, **color** — optional per-series presentation.",
        "- **dataset** — a single chart-pack dataset id.",
        "- **splice_series** `[paleo, instrumental]` + **splice_pair_id** — a",
        "  manifest-keyed splice. `splice_series` must equal the pair's",
        "  `[paleo, instrumental]`; the splice year, resolution note and rebaseline",
        "  legality are all owned by the manifest pair (ADR-020).",
        "- **overlap_policy** — required on a spliced series; must equal the pair's",
        "  manifest `overlap.policy` (review finding #47).",
        "- **rebaseline_to** `{apply_to, alignment_period_ce, alignment_disclosure}` —",
        "  present if and only if the manifest pair records a rebaseline. `apply_to`",
        "  and `alignment_period_ce` must equal the manifest values; the",
        "  `alignment_disclosure` string must equal the manifest",
        "  `rebaseline.disclosure` verbatim, so the alignment method reaches the",
        "  artefact and cannot drift (review finding #50).",
        "- **scale_domain** `[min, max]` — required per series for",
        "  `context_recent_inset` (shared per-axis domains across panels). It must",
        "  contain the plotted data's extent (no clipping, review finding #48); any",
        "  domain that excludes zero requires the `non_zero_baseline` annotation.",
        "- **uncertainty_band** `{lower, upper, source}` — `source` names a member",
        "  dataset of this series (amendment 6).",
        "- **baseline** `{value, label}` — an optional zero/reference line label.",
        "- **transforms** — a list of generic transform ops (see above).",
        "- **annotations** `{splice_point, resolution_note, non_zero_baseline}` — a",
        "  spliced series must carry `splice_point` (with the splice `year_ce`) and",
        "  `resolution_note`. Annotation placement is fixed semantics, not a spec",
        "  choice (amendment 7).",
        "",
        "## Captions",
        "",
        "There is no `caption` field anywhere. Captions (sources, licences, access",
        "date, site URL) are generated by the renderer from the manifest",
        "attribution/licence strings and deployment config, so they cannot drift",
        "from the licensing record and cannot be an injection vector (amendment 9).",
    ]
    # Exactly one trailing newline (end-of-file hook; byte-equality with the
    # committed charts/CHARTSPEC.md).
    return "\n".join(lines) + "\n"
