"""The pure presenter surface (IMPLEMENTATION.md §1: "decisions live in
``ui/presenters.py``").

Issue #18 grew the presenter layer into cohesive pure modules —
``ui.sse_client`` (wire parsing + the transport seam), ``ui.render_model``
(the answer-view fold), ``ui.starter`` (landing page), ``ui.footer``
(ADR-018 chrome), ``ui.charts`` (inline chart views) — and this facade
keeps IMPLEMENTATION.md's single import surface true: the Streamlit
shell imports its decisions from HERE, and the shell-hygiene unit suite
pins that this surface exposes the whole pure contract. No logic lives
in this file.
"""

from __future__ import annotations

from ui.charts import ChartAccessibilityError, ChartView, chart_view_from_event
from ui.footer import (
    NON_AFFILIATION_DISCLAIMER,
    NONCOMMERCIAL_NOTE,
    STEWARD_CREDIT_TEXT,
    TRANSPARENCY_ROUTES,
    FooterInvariantError,
    PageFooter,
    StewardCredit,
    build_page_footer,
    footer_link_line,
    render_footer_lines,
)
from ui.render_model import (
    ANSWER_EVENT,
    BADGE_EVENT,
    CHART_EVENT,
    CITATION_EVENT,
    ERROR_EVENT,
    EVIDENCE_PANEL_HEADING,
    EXCHANGE_REPLAY,
    EXCHANGE_STREAM,
    FEEDBACK_DOWN,
    FEEDBACK_DOWN_LABEL,
    FEEDBACK_NOT_RECORDED_MESSAGE,
    FEEDBACK_RECORDED_MESSAGE,
    FEEDBACK_STATE_RECORDED,
    FEEDBACK_STATE_UNRECORDED,
    FEEDBACK_UP,
    FEEDBACK_UP_LABEL,
    FOOTER_EVENT,
    LIKELIHOOD_TERMS,
    META_EVENT,
    SOURCES_EVENT,
    TEXT_EVENT,
    USAGE_EVENT,
    VALIDATION_DEGRADED_EVENT,
    VIEW_KIND_CACHED,
    VIEW_KIND_CACHED_STARTER,
    VIEW_KIND_CANNED,
    VIEW_KIND_CHART,
    VIEW_KIND_GROUNDED,
    VIEW_KIND_PAUSED,
    VIEW_KIND_REFUSAL,
    VOICES_PANEL_HEADING,
    AnswerView,
    Badge,
    ChatPage,
    CitationChip,
    ErrorNotice,
    ExchangeDecision,
    FeedbackState,
    FeedbackWidget,
    LegendEntry,
    SourceEntry,
    SourcePanelEntry,
    SourcesPanel,
    StreamContractError,
    TermAnchor,
    UncitedFlag,
    annotate_calibrated_terms,
    answer_status_lines,
    build_citation_chips,
    build_sources_panel,
    cached_answer_notice,
    calibrated_term_anchors,
    chat_page_model,
    chips_for_cached_citations,
    feedback_widget_model,
    fold_chat_stream,
    likelihood_legend,
    resolve_exchange,
    resolve_feedback_state,
    source_list,
    stream_text_delta,
    transport_failure_view,
)
from ui.sse_client import (
    ChatTransport,
    FeedbackTransport,
    SseProtocolError,
    TransportError,
    parse_sse_stream,
    stream_chat_events,
)
from ui.starter import (
    SITE_NAME,
    SITE_NAME_SHORT,
    STARTER_GROUP_HEADINGS,
    STARTER_QUESTIONS,
    TAGLINE,
    ChatInputModel,
    ChatSubmission,
    LandingPage,
    StarterGroup,
    chat_input_model,
    free_text_submission,
    landing_page_model,
    starter_groups,
    starter_submission,
)

__all__ = [
    # sse_client
    "ChatTransport",
    "FeedbackTransport",
    "SseProtocolError",
    "TransportError",
    "parse_sse_stream",
    "stream_chat_events",
    # render_model — wire vocabulary + view kinds (finding #233)
    "META_EVENT",
    "ANSWER_EVENT",
    "CHART_EVENT",
    "TEXT_EVENT",
    "CITATION_EVENT",
    "USAGE_EVENT",
    "FOOTER_EVENT",
    "ERROR_EVENT",
    "BADGE_EVENT",
    "VALIDATION_DEGRADED_EVENT",
    "SOURCES_EVENT",
    "VIEW_KIND_GROUNDED",
    "VIEW_KIND_CHART",
    "VIEW_KIND_REFUSAL",
    "VIEW_KIND_CANNED",
    "VIEW_KIND_PAUSED",
    "VIEW_KIND_CACHED_STARTER",
    "VIEW_KIND_CACHED",
    "EXCHANGE_REPLAY",
    "EXCHANGE_STREAM",
    # render_model
    "LIKELIHOOD_TERMS",
    "AnswerView",
    "Badge",
    "ChatPage",
    "CitationChip",
    "ErrorNotice",
    "ExchangeDecision",
    "LegendEntry",
    "SourceEntry",
    "SourcePanelEntry",
    "SourcesPanel",
    "VOICES_PANEL_HEADING",
    "EVIDENCE_PANEL_HEADING",
    "StreamContractError",
    "TermAnchor",
    "UncitedFlag",
    "annotate_calibrated_terms",
    "answer_status_lines",
    "build_citation_chips",
    "build_sources_panel",
    "cached_answer_notice",
    "calibrated_term_anchors",
    "chat_page_model",
    "chips_for_cached_citations",
    "fold_chat_stream",
    "likelihood_legend",
    "resolve_exchange",
    "resolve_feedback_state",
    "source_list",
    "stream_text_delta",
    "transport_failure_view",
    # render_model — thumbs feedback (issue #56)
    "FEEDBACK_UP",
    "FEEDBACK_DOWN",
    "FEEDBACK_UP_LABEL",
    "FEEDBACK_DOWN_LABEL",
    "FEEDBACK_STATE_RECORDED",
    "FEEDBACK_STATE_UNRECORDED",
    "FEEDBACK_RECORDED_MESSAGE",
    "FEEDBACK_NOT_RECORDED_MESSAGE",
    "FeedbackState",
    "FeedbackWidget",
    "feedback_widget_model",
    # starter
    "SITE_NAME",
    "SITE_NAME_SHORT",
    "STARTER_GROUP_HEADINGS",
    "STARTER_QUESTIONS",
    "TAGLINE",
    "ChatInputModel",
    "ChatSubmission",
    "LandingPage",
    "StarterGroup",
    "chat_input_model",
    "free_text_submission",
    "landing_page_model",
    "starter_groups",
    "starter_submission",
    # footer
    "NON_AFFILIATION_DISCLAIMER",
    "NONCOMMERCIAL_NOTE",
    "STEWARD_CREDIT_TEXT",
    "TRANSPARENCY_ROUTES",
    "FooterInvariantError",
    "PageFooter",
    "StewardCredit",
    "build_page_footer",
    "footer_link_line",
    "render_footer_lines",
    # charts
    "ChartAccessibilityError",
    "ChartView",
    "chart_view_from_event",
]
